INSERT INTO users(role_id,full_name,email,password_hash,status) SELECT id,'Usuario cálculo','calculations.user@example.test','hash','APPROVED' FROM roles WHERE code='ADMIN';
INSERT INTO users(role_id,full_name,email,password_hash,status) SELECT id,'Evaluador cálculo','calculations.evaluator@example.test','hash','APPROVED' FROM roles WHERE code='EVALUATOR';
DO $$
DECLARE u uuid; evaluator uuid; contact_uuid uuid; co uuid; es uuid; req uuid; ca uuid; ass uuid; ins uuid; tpl uuid; tv uuid; section_uuid uuid; subsection_uuid uuid; item uuid; rs uuid; rv uuid; f uuid; factor_id uuid; cat uuid; sub uuid; calc uuid; i int; j int; codes text[]:=ARRAY['VOLUME','HACCP','BPM','INABIE','REJECTIONS','SAMPLING']; weights numeric[]:=ARRAY[.2,.2,.15,.15,.15,.15]; oc text[]:=ARRAY['LOW','MEDIUM_LOW','MEDIUM_HIGH','HIGH']; os numeric[]:=ARRAY[1,1.67,2.33,3];
BEGIN
 SELECT id INTO u FROM users WHERE email_normalized='calculations.user@example.test';
 SELECT id INTO evaluator FROM users WHERE email_normalized='calculations.evaluator@example.test';
 INSERT INTO bpm_templates(code,name) VALUES('CALCULATIONS_TEST','BPM cálculos') RETURNING id INTO tpl; INSERT INTO bpm_template_versions(template_id,version_number) VALUES(tpl,1) RETURNING id INTO tv; INSERT INTO bpm_template_items(template_version_id,title,sort_order,item_kind) VALUES(tv,'Sección',1,'SECTION') RETURNING id INTO section_uuid; INSERT INTO bpm_template_items(template_version_id,parent_item_id,title,sort_order,item_kind) VALUES(tv,section_uuid,'Subsección',1,'SUBSECTION') RETURNING id INTO subsection_uuid; INSERT INTO bpm_template_items(template_version_id,parent_item_id,title,sort_order,item_kind,is_evaluable,default_criticality) VALUES(tv,subsection_uuid,'Criterio',1,'CRITERION',true,'MAYOR') RETURNING id INTO item; UPDATE bpm_template_versions SET status='PUBLISHED',published_at=clock_timestamp(),published_by_user_id=u WHERE id=tv;
 INSERT INTO risk_rule_sets(code,name) VALUES('CALCULATIONS_TEST','Riesgo cálculos') RETURNING id INTO rs; INSERT INTO risk_rule_versions(risk_rule_set_id,version_number) VALUES(rs,1) RETURNING id INTO rv;
 FOR i IN 1..6 LOOP INSERT INTO risk_factors(risk_rule_version_id,code,name,weight,sort_order) VALUES(rv,codes[i],codes[i],weights[i],i) RETURNING id INTO f; FOR j IN 1..4 LOOP INSERT INTO risk_factor_options(risk_factor_id,code,label,score,sort_order) VALUES(f,oc[j],oc[j],os[j],j); END LOOP; END LOOP;
 INSERT INTO food_risk_categories(risk_rule_version_id,code,name,sort_order) VALUES(rv,'CALC_FOOD','Alimento cálculo',1) RETURNING id INTO cat; INSERT INTO food_risk_subcategories(category_id,name,microbiological_risk,risk_score,sort_order) VALUES(cat,'Producto cálculo','HIGH',3,1) RETURNING id INTO sub;
 INSERT INTO inspection_frequency_ranges(risk_rule_version_id,lower_bound,upper_bound,lower_inclusive,upper_inclusive,frequency,label,sort_order) VALUES(rv,1,3.6,true,true,'ANNUAL','Anual',1),(rv,3.6,6.3,false,true,'SEMIANNUAL','Semestral',2),(rv,6.3,NULL,false,false,'QUARTERLY','Trimestral',3); UPDATE risk_rule_versions SET status='PUBLISHED',published_at=clock_timestamp(),published_by_user_id=u WHERE id=rv;
 INSERT INTO companies(legal_name,rnc) VALUES('Empresa cálculos','136-55555-5') RETURNING id INTO co; INSERT INTO establishments(company_id,name) VALUES(co,'Planta cálculos') RETURNING id INTO es; INSERT INTO company_requests(company_id,establishment_id,reason) VALUES(co,es,'Solicitud cálculo') RETURNING id INTO req; INSERT INTO contacts(full_name) VALUES('Contacto cálculos') RETURNING id INTO contact_uuid; INSERT INTO request_contacts(request_id,contact_id,relationship_type,full_name_snapshot,is_primary) VALUES(req,contact_uuid,'PRIMARY_CONTACT','Contacto cálculos',true); INSERT INTO request_documents(request_id,document_type,storage_path,file_name,mime_type,size_bytes,status,validated_at,validated_by_user_id) VALUES(req,'AUTHORIZATION_LETTER','requests/calc.pdf','calc.pdf','application/pdf',1,'VALID',clock_timestamp(),u); UPDATE company_requests SET status='PENDING_ASSIGNMENT',submitted_at=clock_timestamp() WHERE id=req; INSERT INTO cases(origin,request_id,company_id,establishment_id,status) VALUES('COMPANY_REQUEST',req,co,es,'PENDING_ASSIGNMENT') RETURNING id INTO ca; INSERT INTO case_assignments(case_id,evaluator_user_id,assigned_by_user_id) VALUES(ca,evaluator,u) RETURNING id INTO ass; SET CONSTRAINTS ALL IMMEDIATE; SET CONSTRAINTS ALL DEFERRED;
 INSERT INTO inspections(case_id,case_assignment_id,evaluator_user_id,bpm_template_version_id,risk_rule_version_id,created_by_user_id) VALUES(ca,ass,evaluator,tv,rv,u) RETURNING id INTO ins; UPDATE inspections SET status='IN_PROGRESS',started_at=clock_timestamp() WHERE id=ins; INSERT INTO inspection_bpm_responses(inspection_id,bpm_item_id,response_value) VALUES(ins,item,'C'); FOR factor_id IN SELECT id FROM risk_factors WHERE risk_rule_version_id=rv LOOP INSERT INTO inspection_risk_factor_selections(inspection_id,risk_factor_id,risk_factor_option_id) SELECT ins,factor_id,id FROM risk_factor_options WHERE risk_factor_id=factor_id ORDER BY score LIMIT 1; END LOOP; INSERT INTO inspection_food_snapshots(inspection_id,food_risk_subcategory_id,category_code_snapshot,category_name_snapshot,subcategory_name_snapshot,microbiological_risk_snapshot,risk_score_snapshot) VALUES(ins,sub,'CALC_FOOD','Alimento cálculo','Producto cálculo','HIGH',3); UPDATE inspections SET status='PENDING_SUBMISSION',finalized_at=clock_timestamp() WHERE id=ins; UPDATE inspections SET status='SUBMITTED',submitted_at=clock_timestamp() WHERE id=ins;
 calc:=recalculate_inspection(ins,u,'Cálculo inicial'); IF NOT EXISTS(SELECT 1 FROM inspection_calculations WHERE id=calc AND frequency='ANNUAL' AND is_current) THEN RAISE EXCEPTION 'calculation result invalid'; END IF; PERFORM recalculate_inspection(ins,u,'Recálculo'); IF (SELECT count(*) FROM inspection_calculations WHERE inspection_id=ins)<>2 OR (SELECT count(*) FROM inspection_calculations WHERE inspection_id=ins AND is_current)<>1 THEN RAISE EXCEPTION 'calculation history invalid'; END IF;
END $$;
