import { cellValue, findHeaderRow, loadSourceFile, loadWorkbook } from './files.js';
import { canonicalJson, emptyCounts, normalizeCode, normalizeNumber, normalizeText, sha256, slugCode, type ImportBreakdown, type ImportIssue, type SourceFile } from './model.js';
import type { RiskManifest } from './manifests.js';

type RiskLevel='LOW'|'MEDIUM'|'HIGH'|null;
const riskLevels:Record<string,{level:RiskLevel;score:number|null}>={BAJO:{level:'LOW',score:1},LOW:{level:'LOW',score:1},MEDIO:{level:'MEDIUM',score:2},MEDIUM:{level:'MEDIUM',score:2},ALTO:{level:'HIGH',score:3},HIGH:{level:'HIGH',score:3},NA:{level:null,score:null},'N/A':{level:null,score:null}};
const factorCodes:Record<string,string>={'VOLUMEN DE PRODUCCION':'VOLUME','IMPLEMENTACION SISTEMA HACCP':'HACCP','CUMPLIMIENTO CON LAS BPM':'BPM','PROVEEDOR INABIE':'INABIE','RECHAZOS REGISTROS SANITARIOS POR INCUMPLIMIENTO MICROBIOLOGICOS':'REJECTIONS','PLANES DE MUESTREO MICROBIOLOGICO/ANALISIS DE LABORATORIO':'SAMPLING'};
const frequencyCodes:Record<string,string>={ANUAL:'ANNUAL',SEMESTRAL:'SEMIANNUAL',TRIMESTRAL:'QUARTERLY'};
const plain=(value:unknown)=>normalizeCode(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const optionCode=(score:number)=>score===1?'LOW':score===1.67?'MEDIUM_LOW':score===2.33?'MEDIUM_HIGH':'HIGH';
const sourceCounts=(keys:string[],issues:ImportIssue[],prefix:string)=>{const rejected=new Set(issues.filter(issue=>issue.severity==='ERROR'&&issue.recordKey?.startsWith(prefix)).map(issue=>issue.recordKey)),warned=new Set(issues.filter(issue=>issue.severity==='WARNING'&&issue.recordKey?.startsWith(prefix)).map(issue=>issue.recordKey));return{...emptyCounts(),read:keys.length,accepted:keys.filter(key=>!rejected.has(key)).length,rejected:rejected.size,warned:warned.size}};

function percentageRange(label:string){const normalized=label.replaceAll(',','.').replace(/\s+/g,' ').trim(),numbers=[...normalized.matchAll(/\d+(?:\.\d+)?/g)].map(match=>Number(match[0]));if(/[≤<]=?\s*\d/.test(normalized)&&numbers.length)return{lower:0,upper:numbers[0]};if(numbers.length>=2)return{lower:numbers[0],upper:numbers[1]};return null}

export async function parseRiskPackage(manifest:RiskManifest){
  const issues:ImportIssue[]=[],files:SourceFile[]=[],transformations=['NFKC, espacios, códigos y números normalizados antes del hash funcional.','Columnas posteriores al primer Puntaje de la matriz ignoradas estrictamente.','BAJO/MEDIO/ALTO/NA convertidos a LOW=1, MEDIUM=2, HIGH=3 y NA=NULL.','Rangos almacenados con límites e inclusividad explícitos.'];
  const matrixLoaded=await loadSourceFile(manifest.matrix.logicalName,manifest.matrix.path);files.push(matrixLoaded.source);const matrixBook=await loadWorkbook(matrixLoaded.bytes),matrixSheet=matrixBook.getWorksheet(manifest.matrix.sheet??'')??matrixBook.worksheets[0];if(!matrixSheet)throw new Error('MATRIX_SHEET_NOT_FOUND');
  const header=findHeaderRow(matrixSheet,['CATEGORIA','SUBCATEGORIA','RIESGO MICROBIOLOGICO','PUNTAJE']),categories:any[]=[],categoryByName=new Map<string,any>(),matrixKeys:string[]=[],usedStandalone=new Set<number>();
  if(!header)issues.push({severity:'ERROR',code:'MATRIX_HEADERS_MISSING',message:'No se encontraron las cuatro cabeceras oficiales.',file:matrixLoaded.source.fileName,sheet:matrixSheet.name});else{const column=(key:string)=>header.columns.get(key)!;
    for(let rowNumber=header.rowNumber+1;rowNumber<=matrixSheet.rowCount;rowNumber+=1){const row=matrixSheet.getRow(rowNumber),category=normalizeText(cellValue(row.getCell(column('CATEGORIA')))),originalSubcategory=normalizeText(cellValue(row.getCell(column('SUBCATEGORIA')))),rawRisk=plain(cellValue(row.getCell(column('RIESGO MICROBIOLOGICO'))))||'NA',scoreCell=row.getCell(column('PUNTAJE')),scoreValue=scoreCell.value as any,isFormula=Boolean(scoreValue&&typeof scoreValue==='object'&&('formula' in scoreValue||'sharedFormula' in scoreValue)),supplied=isFormula?null:normalizeNumber(cellValue(scoreCell));if(!category&&!originalSubcategory&&!normalizeText(cellValue(row.getCell(column('RIESGO MICROBIOLOGICO'))))&&supplied===null)continue;
      const recordKey=`foodMatrix:${matrixSheet.name}:${rowNumber}`;matrixKeys.push(recordKey);let subcategory=originalSubcategory,mapping=riskLevels[rawRisk];const exception=manifest.standaloneCategoryLeaves.find(item=>item.sourceRow===rowNumber);
      if(exception){usedStandalone.add(rowNumber);const valid=normalizeText(category)===normalizeText(exception.expectedCategory)&&originalSubcategory===''&&rawRisk===plain(exception.expectedRisk)&&Boolean(mapping)&&mapping!.score===exception.expectedScore&&(supplied===null||supplied===exception.expectedScore);if(!valid){issues.push({severity:'ERROR',code:'STALE_STANDALONE_CATEGORY_EXCEPTION',message:'La fila ya no coincide con la categoría, subcategoría vacía, riesgo y puntaje declarados por la excepción.',file:matrixLoaded.source.fileName,sheet:matrixSheet.name,row:rowNumber,field:'standaloneCategoryLeaves',recordKey});continue}subcategory=normalizeText(exception.subcategory);transformations.push(`Excepción fila ${rowNumber}: ${category} se importó como categoría con hoja ${subcategory}.`)}
      if(!category||!subcategory){issues.push({severity:'ERROR',code:'MATRIX_REQUIRED_FIELD',message:'Categoría y subcategoría son obligatorias salvo excepción explícita.',file:matrixLoaded.source.fileName,sheet:matrixSheet.name,row:rowNumber,recordKey});continue}
      if(!mapping){issues.push({severity:'ERROR',code:'UNKNOWN_MICROBIOLOGICAL_RISK',message:'Riesgo microbiológico desconocido.',file:matrixLoaded.source.fileName,sheet:matrixSheet.name,row:rowNumber,column:'RIESGO MICROBIOLÓGICO',recordKey});continue}
      if(supplied!==null&&supplied!==mapping.score){issues.push({severity:'ERROR',code:'RISK_SCORE_MISMATCH',message:'Puntaje incompatible con la escala microbiológica oficial.',file:matrixLoaded.source.fileName,sheet:matrixSheet.name,row:rowNumber,column:'Puntaje',recordKey});continue}
      const key=normalizeCode(category);let parent=categoryByName.get(key);if(!parent){parent={code:slugCode(category,`CATEGORY_${categories.length+1}`),name:category,sortOrder:categories.length+1,sourceFile:matrixLoaded.source.fileName,sourceSheet:matrixSheet.name,sourceRowNumber:rowNumber,subcategories:[]};categoryByName.set(key,parent);categories.push(parent)}
      if(parent.subcategories.some((item:any)=>normalizeCode(item.name)===normalizeCode(subcategory)))issues.push({severity:'ERROR',code:'DUPLICATE_SUBCATEGORY',message:'Subcategoría duplicada dentro de la categoría.',file:matrixLoaded.source.fileName,sheet:matrixSheet.name,row:rowNumber,recordKey});else parent.subcategories.push({name:subcategory,microbiologicalRisk:mapping.level,riskScore:mapping.score,sortOrder:parent.subcategories.length+1,sourceFile:matrixLoaded.source.fileName,sourceSheet:matrixSheet.name,sourceRowNumber:rowNumber});
    }
  }
  for(const exception of manifest.standaloneCategoryLeaves)if(!usedStandalone.has(exception.sourceRow))issues.push({severity:'ERROR',code:'STANDALONE_CATEGORY_EXCEPTION_TARGET_MISSING',message:`No se encontró la fila ${exception.sourceRow} declarada como hoja autónoma.`,file:matrixLoaded.source.fileName,sheet:matrixSheet.name,field:'standaloneCategoryLeaves',recordKey:`foodMatrix:${matrixSheet.name}:${exception.sourceRow}`});
  const rulesLoaded=await loadSourceFile(manifest.rules.logicalName,manifest.rules.path);files.push(rulesLoaded.source);const rulesBook=await loadWorkbook(rulesLoaded.bytes),rulesSheet=rulesBook.getWorksheet(manifest.rules.sheet??'')??rulesBook.worksheets[0];if(!rulesSheet)throw new Error('RULES_SHEET_NOT_FOUND');
  const factorHeader=findHeaderRow(rulesSheet,['FACTOR DE RIESGO','PUNTAJE','PESO %']),factors:any[]=[],factorKeys:string[]=[];
  if(!factorHeader)issues.push({severity:'ERROR',code:'FACTOR_HEADERS_MISSING',message:'No se encontró la tabla semántica de factores.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name});else{const nameCol=factorHeader.columns.get('FACTOR DE RIESGO')!,weightCol=factorHeader.columns.get('PESO %')!;for(let rowNumber=factorHeader.rowNumber+1;rowNumber<=rulesSheet.rowCount&&factors.length<6;rowNumber+=1){const name=normalizeText(cellValue(rulesSheet.getRow(rowNumber).getCell(nameCol)));if(!name)continue;const recordKey=`riskFactors:factor:${rowNumber}`;factorKeys.push(recordKey);const code=factorCodes[plain(name)];if(!code){issues.push({severity:'ERROR',code:'UNKNOWN_FACTOR',message:'Factor de riesgo desconocido.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,row:rowNumber,recordKey});continue}const weight=normalizeNumber(cellValue(rulesSheet.getRow(rowNumber).getCell(weightCol)));if(weight===null||weight<=0||weight>1)issues.push({severity:'ERROR',code:'INVALID_WEIGHT',message:'Peso inválido.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,row:rowNumber,column:'Peso %',recordKey});factors.push({code,name,weight,sortOrder:factors.length+1,options:[]})}}
  const optionColumn=rulesSheet.getColumn(manifest.factorOptionColumn).number;
  for(const configured of manifest.factorOptionRanges){const factor=factors.find(item=>item.code===configured.factorCode);if(!factor)continue;for(let rowNumber=configured.startRow;rowNumber<=configured.endRow;rowNumber+=1){const label=normalizeText(cellValue(rulesSheet.getRow(rowNumber).getCell(optionColumn)));if(!label)continue;const recordKey=`riskFactors:option:${configured.factorCode}:${rowNumber}`;factorKeys.push(recordKey);const matched=/\((1(?:\.00)?|1\.67|2\.33|3(?:\.00)?)\s*(?:p|punto)/i.exec(label);if(!matched){issues.push({severity:'ERROR',code:'OPTION_SCORE_MISSING',message:'La opción no contiene un puntaje oficial reconocible.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,row:rowNumber,column:manifest.factorOptionColumn,recordKey});continue}const score=Number(matched[1]);factor.options.push({code:optionCode(score),label:label.replace(/\s*\([^)]*\)\s*$/,'').trim(),score,sortOrder:factor.options.length+1,source:'FILE',recordKey})}}
  for(const configured of manifest.additionalFactorOptions){const factor=factors.find(item=>item.code===configured.factorCode),recordKey=`riskFactors:manifest:${configured.factorCode}:${configured.code}`;factorKeys.push(recordKey);if(!factor){issues.push({severity:'ERROR',code:'ADDITIONAL_OPTION_FACTOR_MISSING',message:'El factor de la opción adicional no existe en la fuente.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,field:'additionalFactorOptions',recordKey});continue}if(factor.options.some((item:any)=>item.code===configured.code||item.score===configured.score||plain(item.label)===plain(configured.label))){issues.push({severity:'ERROR',code:'DUPLICATE_FACTOR_OPTION',message:'La opción adicional duplica código, puntaje o etiqueta.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,field:'additionalFactorOptions',recordKey});continue}factor.options.push({...configured,sortOrder:factor.options.length+1,source:'MANIFEST',recordKey});transformations.push(`Opción explícita ${configured.factorCode}: ${configured.label} = ${configured.score} (${configured.code}).`)}
  for(const factor of factors){const factorRecord=`riskFactors:factor:${factor.sortOrder}`;const actual=factor.options.map((item:any)=>item.score).sort((a:number,b:number)=>a-b);if(JSON.stringify(actual)!==JSON.stringify([1,1.67,2.33,3]))issues.push({severity:'ERROR',code:'INVALID_FACTOR_OPTIONS',message:`${factor.code} no contiene exactamente los cuatro puntajes oficiales.`,file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:factor.options[0]?.recordKey??factorRecord});const hasBpmAddition=factor.code==='BPM'&&manifest.additionalFactorOptions.some(item=>item.factorCode==='BPM');if(hasBpmAddition){const sourceScores=factor.options.filter((item:any)=>item.source==='FILE').map((item:any)=>item.score);if(JSON.stringify(sourceScores)!==JSON.stringify([3,2.33,1.67]))issues.push({severity:'ERROR',code:'BPM_SOURCE_OPTIONS_CHANGED',message:'Las tres opciones BPM de la fuente ya no coinciden exactamente con 3, 2.33 y 1.67.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:factor.options[0]?.recordKey??factorRecord});const ranges=factor.options.map((item:any)=>({item,range:percentageRange(item.label)}));if(ranges.some((entry:any)=>!entry.range))issues.push({severity:'ERROR',code:'BPM_OPTION_RANGE_INVALID',message:'Todas las opciones BPM deben declarar un rango porcentual reconocible.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:factor.options.find((item:any)=>!percentageRange(item.label))?.recordKey});else{const ordered=ranges.sort((a:any,b:any)=>a.range!.lower-b.range!.lower);for(let index=1;index<ordered.length;index+=1)if(ordered[index].range!.lower!==ordered[index-1].range!.upper+1)issues.push({severity:'ERROR',code:'BPM_OPTION_RANGE_GAP_OR_OVERLAP',message:'Los rangos porcentuales BPM contienen un hueco o solapamiento.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:ordered[index].item.recordKey});if(ordered[0].range!.lower!==0||ordered.at(-1)!.range!.upper!==100)issues.push({severity:'ERROR',code:'BPM_OPTION_RANGE_INCOMPLETE',message:'Los rangos BPM deben cubrir de 0% a 100%.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:ordered[0].item.recordKey})}}}
  if(factors.length!==6||new Set(factors.map(item=>item.code)).size!==6)issues.push({severity:'ERROR',code:'INVALID_FACTOR_SET',message:'Deben existir exactamente los seis factores oficiales.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:factorKeys[0]});const weightSum=Number(factors.reduce((sum,item)=>sum+(item.weight??0),0).toFixed(4));if(weightSum!==1)issues.push({severity:'ERROR',code:'INVALID_WEIGHT_SUM',message:'Los pesos de los seis factores deben sumar 1.0000.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:factorKeys[0]});
  const ranges:any[]=[],rangeKeys:string[]=[];for(let rowNumber=1;rowNumber<=rulesSheet.rowCount;rowNumber+=1){const rangeText=normalizeText(cellValue(rulesSheet.getRow(rowNumber).getCell(1))),frequency=normalizeText(cellValue(rulesSheet.getRow(rowNumber).getCell(16)));if(!rangeText||!frequencyCodes[plain(frequency)])continue;const numbers=[...rangeText.replaceAll(',','.').matchAll(/\d+(?:\.\d+)?/g)].map(item=>Number(item[0]));if(!numbers.length)continue;const recordKey=`frequencyRanges:${rowNumber}`;rangeKeys.push(recordKey);const open=/^\s*>/.test(rangeText),lower=numbers[0],upper=numbers.length>1?numbers[1]:null;ranges.push({lowerBound:lower,upperBound:upper,lowerInclusive:!open,upperInclusive:upper!==null,frequency:frequencyCodes[plain(frequency)],label:frequency,sortOrder:ranges.length+1,sourceRowNumber:rowNumber,recordKey})}
  if(ranges.length!==3)issues.push({severity:'ERROR',code:'INVALID_FREQUENCY_RANGES',message:'Se esperaban exactamente tres rangos de frecuencia.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,recordKey:rangeKeys[0]});for(let index=1;index<ranges.length;index+=1)if(ranges[index-1].upperBound!==ranges[index].lowerBound||ranges[index-1].upperInclusive===ranges[index].lowerInclusive)issues.push({severity:'ERROR',code:'RANGE_GAP_OR_OVERLAP',message:'Los límites de frecuencia tienen huecos o solapamientos.',file:rulesLoaded.source.fileName,sheet:rulesSheet.name,row:ranges[index].sourceRowNumber,recordKey:ranges[index].recordKey});
  const breakdown:ImportBreakdown={foodMatrix:sourceCounts(matrixKeys,issues,'foodMatrix:'),riskFactors:sourceCounts(factorKeys,issues,'riskFactors:'),frequencyRanges:sourceCounts(rangeKeys,issues,'frequencyRanges:')};const functional={catalog:{code:normalizeCode(manifest.catalog.code),name:normalizeText(manifest.catalog.name)},riskRuleSet:{code:normalizeCode(manifest.riskRuleSet.code),name:normalizeText(manifest.riskRuleSet.name)},categories,factors:factors.map(factor=>({...factor,options:factor.options.map(({source:_,recordKey:__,...option}:any)=>option)})),ranges:ranges.map(({recordKey:_,...range})=>range)};const fileBundle=files.map(file=>({logicalName:file.logicalName,sha256:file.sha256})).sort((a,b)=>a.logicalName.localeCompare(b.logicalName));const summary={categories:categories.length,subcategories:categories.reduce((sum,item)=>sum+item.subcategories.length,0),factors:factors.length,factorOptions:factors.reduce((sum,item)=>sum+item.options.length,0),frequencyRanges:ranges.length};return{functional,files,issues,breakdown,summary,packageHash:sha256(canonicalJson(fileBundle)),functionalHash:sha256(canonicalJson(functional)),transformations};
}
