import type{QueryResult,QueryResultRow}from'pg';import type{CreateInput,ListInput,PatchInput}from'./schemas.js';
type Runner={query:<T extends QueryResultRow>(sql:string,values?:unknown[])=>Promise<QueryResult<T>>};
export const requestProjection=`SELECT r.id,r.company_id AS "companyId",r.establishment_id AS "establishmentId",e.name AS "establishmentName",r.request_type AS "requestType",r.reason,r.observations,r.status::text,r.submitted_at AS "submittedAt",r.created_by_user_id AS "createdByUserId",r.version,r.created_at AS "createdAt",r.updated_at AS "updatedAt" FROM company_requests r JOIN establishments e ON e.id=r.establishment_id`;
export const documentProjection=`SELECT id,request_id AS "requestId",document_type AS "documentType",mime_type AS "mimeType",size_bytes::int AS "sizeBytes",status::text,uploaded_at AS "uploadedAt",validated_at AS "validatedAt",validated_by_user_id AS "validatedByUserId",rejection_reason AS "rejectionReason",archived_at AS "archivedAt",version,created_at AS "createdAt",updated_at AS "updatedAt"`;
export async function membership(r:Runner,user:string){const q=await r.query<{companyId:string}>('SELECT m.company_id AS "companyId" FROM user_company_memberships m JOIN companies c ON c.id=m.company_id WHERE m.user_id=$1 AND m.effective_to IS NULL AND c.status=\'ACTIVE\'',[user]);return q.rows[0]?.companyId}
export async function organization(r:Runner,est:string){const q=await r.query<{companyStatus:string;establishmentStatus:string;companyId:string}>('SELECT c.status::text AS "companyStatus",e.status::text AS "establishmentStatus",e.company_id AS "companyId" FROM establishments e JOIN companies c ON c.id=e.company_id WHERE e.id=$1',[est]);return q.rows[0]}
export async function find(r:Runner,x:string,lock=false){const q=await r.query(`${requestProjection} WHERE r.id=$1${lock?' FOR UPDATE OF r':''}`,[x]);return q.rows[0] as any}
export async function insert(r:Runner,i:CreateInput,company:string,user:string){const q=await r.query<{id:string}>('INSERT INTO company_requests(company_id,establishment_id,request_type,reason,observations,status,created_by_user_id) VALUES($1,$2,$3,$4,$5,\'DRAFT\',$6) RETURNING id',[company,i.establishmentId,i.requestType,i.reason,i.observations??null,user]);return q.rows[0].id}
export async function list(r:Runner,i:ListInput,scope?:string){const p=i.search?`%${i.search.toLowerCase()}%`:null,w=' WHERE ($1::uuid IS NULL OR r.company_id=$1) AND ($2::request_status IS NULL OR r.status=$2) AND ($3::uuid IS NULL OR r.establishment_id=$3) AND ($4::text IS NULL OR r.request_type=$4) AND ($5::text IS NULL OR lower(r.request_type) LIKE $5 OR lower(r.reason) LIKE $5)';const vals=[scope??null,i.status??null,i.establishmentId??null,i.requestType??null,p];const c=await r.query<{total:string}>(`SELECT count(*) total FROM company_requests r${w}`,vals);const q=await r.query(`${requestProjection}${w} ORDER BY r.created_at DESC LIMIT $6 OFFSET $7`,[...vals,i.limit,(i.page-1)*i.limit]);return{rows:q.rows,total:Number(c.rows[0]?.total??0)}}
export async function update(r:Runner,x:string,i:PatchInput){const q=await r.query('UPDATE company_requests SET establishment_id=COALESCE($1,establishment_id),request_type=COALESCE($2,request_type),reason=COALESCE($3,reason),observations=CASE WHEN $4 THEN $5 ELSE observations END WHERE id=$6 AND version=$7 AND status=\'DRAFT\'',[i.establishmentId??null,i.requestType??null,i.reason??null,i.observations!==undefined,i.observations??null,x,i.version]);return Boolean(q.rowCount)}
export async function contacts(r:Runner,x:string){const q=await r.query('SELECT rc.id,rc.contact_id AS "contactId",rc.relationship_type AS "relationshipType",rc.full_name_snapshot AS "fullName",rc.phone_snapshot AS phone,rc.email_snapshot AS email,rc.is_primary AS "isPrimary",rc.removed_at AS "removedAt",rc.version,rc.created_at AS "createdAt" FROM request_contacts rc WHERE rc.request_id=$1 ORDER BY rc.created_at',[x]);return q.rows}
export async function addContact(r:Runner,x:string,c:string,t:string,p:boolean){const q=await r.query<{id:string}>('INSERT INTO request_contacts(request_id,contact_id,relationship_type,full_name_snapshot,phone_snapshot,email_snapshot,is_primary) SELECT $1,id,$3,full_name,phone,email,$4 FROM contacts WHERE id=$2 RETURNING id',[x,c,t,p]);return q.rows[0]?.id}
export async function contactAllowed(r:Runner,c:string,company:string){const q=await r.query('SELECT 1 FROM company_contacts WHERE contact_id=$1 AND company_id=$2 UNION ALL SELECT 1 FROM establishment_contacts ec JOIN establishments e ON e.id=ec.establishment_id WHERE ec.contact_id=$1 AND e.company_id=$2 LIMIT 1',[c,company]);return Boolean(q.rowCount)}
export async function removeContact(r:Runner,x:string,id:string,v:number,user:string){const q=await r.query('UPDATE request_contacts SET removed_at=clock_timestamp(),removed_by_user_id=$1 WHERE id=$2 AND request_id=$3 AND version=$4 AND removed_at IS NULL',[user,id,x,v]);return Boolean(q.rowCount)}
export async function documents(r:Runner,x:string,includePath=false){const q=await r.query(`${documentProjection}${includePath?',storage_path AS "storagePath"':''} FROM request_documents WHERE request_id=$1 ORDER BY created_at DESC`,[x]);return q.rows as any[]}
export async function document(r:Runner,x:string,id:string,lock=false,includePath=false){const q=await r.query(`${documentProjection}${includePath?',storage_path AS "storagePath"':''} FROM request_documents WHERE request_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[x,id]);return q.rows[0] as any}
export async function insertDocument(r:Runner,x:string,t:string,path:string,name:string,mime:string,size:number){const q=await r.query<{id:string}>('INSERT INTO request_documents(request_id,document_type,storage_path,file_name,mime_type,size_bytes,status) VALUES($1,$2,$3,$4,$5,$6,\'PENDING\') RETURNING id',[x,t,path,name,mime,size]);return q.rows[0].id}
export async function activeDocumentCount(r:Runner,x:string){const q=await r.query<{count:string;letter:string}>('SELECT count(*)::text count,count(*) FILTER(WHERE document_type=\'AUTHORIZATION_LETTER\' AND status<>\'ARCHIVED\')::text letter FROM request_documents WHERE request_id=$1 AND deleted_at IS NULL AND status<>\'ARCHIVED\'',[x]);return{count:Number(q.rows[0].count),letter:Number(q.rows[0].letter)}}
export async function changeDocument(r:Runner,x:string,id:string,v:number,status:string,user:string,reason?:string){const q=await r.query(`UPDATE request_documents SET status=$1,validated_at=CASE WHEN $1 IN('VALID','REJECTED') THEN clock_timestamp() ELSE validated_at END,validated_by_user_id=CASE WHEN $1 IN('VALID','REJECTED') THEN $2 ELSE validated_by_user_id END,rejection_reason=CASE WHEN $1='REJECTED' THEN $3 ELSE rejection_reason END,archived_at=CASE WHEN $1='ARCHIVED' THEN clock_timestamp() ELSE archived_at END,archived_by_user_id=CASE WHEN $1='ARCHIVED' THEN $2 ELSE archived_by_user_id END,deleted_at=CASE WHEN $1='ARCHIVED' THEN clock_timestamp() ELSE deleted_at END WHERE request_id=$4 AND id=$5 AND version=$6`,[status,user,reason??null,x,id,v]);return Boolean(q.rowCount)}
export async function submit(r:Runner,x:string,v:number){const q=await r.query('UPDATE company_requests SET status=\'PENDING_ASSIGNMENT\',submitted_at=clock_timestamp() WHERE id=$1 AND version=$2 AND status=\'DRAFT\' RETURNING id',[x,v]);return Boolean(q.rowCount)}
export async function createCase(r:Runner,req:any){const q=await r.query<{id:string}>('INSERT INTO cases(origin,request_id,company_id,establishment_id,priority,status) VALUES(\'COMPANY_REQUEST\',$1,$2,$3,\'MEDIUM\',\'PENDING_ASSIGNMENT\') RETURNING id',[req.id,req.companyId,req.establishmentId]);return q.rows[0].id}
