DROP TRIGGER IF EXISTS inspection_review_events_immutable ON inspection_review_events;
DROP TRIGGER IF EXISTS inspection_bpm_responses_mark_correction ON inspection_bpm_responses;
DROP TRIGGER IF EXISTS report_participants_guard ON inspection_report_participants;
DROP TRIGGER IF EXISTS reviews_version ON inspection_review_cycles;
DROP TRIGGER IF EXISTS reports_version ON inspection_reports;
DROP FUNCTION IF EXISTS officialize_inspection_report(uuid,uuid,uuid);
DROP FUNCTION IF EXISTS resubmit_inspection_review(uuid,uuid,uuid);
DROP FUNCTION IF EXISTS return_inspection_review(uuid,uuid,uuid,text,uuid[]);
DROP FUNCTION IF EXISTS approve_inspection_review(uuid,uuid,uuid,text);
DROP FUNCTION IF EXISTS open_inspection_review(uuid,uuid);
DROP FUNCTION IF EXISTS mark_review_correction_item();
DROP FUNCTION IF EXISTS report_participant_guard();
DROP FUNCTION IF EXISTS immutable_review_event();
DROP FUNCTION IF EXISTS review_actor_is_global(uuid);
DROP FUNCTION IF EXISTS review_role_of(uuid);

DROP TRIGGER IF EXISTS reviews_guard ON inspection_review_cycles;
DROP TRIGGER IF EXISTS correction_guard ON inspection_review_correction_items;
DROP TRIGGER IF EXISTS reports_guard ON inspection_reports;

DROP TABLE inspection_report_participants;
DROP INDEX IF EXISTS inspection_reports_one_active_draft_idx;
ALTER TABLE inspection_reports DROP CONSTRAINT IF EXISTS inspection_reports_archive_check;
ALTER TABLE inspection_reports DROP CONSTRAINT IF EXISTS inspection_reports_generation_key_key;
ALTER TABLE inspection_reports DROP CONSTRAINT IF EXISTS inspection_reports_verification_id_key;
ALTER TABLE inspection_reports DROP COLUMN updated_at,DROP COLUMN version,DROP COLUMN archived_by_user_id,DROP COLUMN archived_at,DROP COLUMN verification_id,DROP COLUMN generation_key,DROP COLUMN review_cycle_id;
ALTER TABLE inspection_review_events DROP COLUMN calculation_id;
ALTER TABLE inspection_review_correction_items DROP CONSTRAINT IF EXISTS inspection_review_correction_items_cycle_return_item_key;
ALTER TABLE inspection_review_correction_items DROP COLUMN corrected_response_version,DROP COLUMN response_version_at_return,DROP COLUMN return_number;
ALTER TABLE inspection_review_correction_items ADD CONSTRAINT inspection_review_correction_items_review_cycle_id_bpm_item_key UNIQUE(review_cycle_id,bpm_item_id);
ALTER TABLE inspection_review_cycles DROP COLUMN updated_at,DROP COLUMN version,DROP COLUMN approved_by_role_snapshot,DROP COLUMN approved_by_name_snapshot,DROP COLUMN return_count,DROP COLUMN current_calculation_id,DROP COLUMN initial_calculation_id;

CREATE OR REPLACE FUNCTION review_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='INSERT' THEN IF NOT EXISTS(SELECT 1 FROM inspections WHERE id=NEW.inspection_id AND status='SUBMITTED') THEN RAISE EXCEPTION 'review requires submitted inspection'; END IF; RETURN NEW; END IF; IF OLD.status='APPROVED' OR NOT ((OLD.status='PENDING_REVIEW' AND NEW.status IN('RETURNED_FOR_CORRECTION','APPROVED')) OR (OLD.status='RETURNED_FOR_CORRECTION' AND NEW.status='RESUBMITTED') OR (OLD.status='RESUBMITTED' AND NEW.status IN('RETURNED_FOR_CORRECTION','APPROVED'))) THEN RAISE EXCEPTION 'invalid review transition'; END IF; IF NEW.status='RETURNED_FOR_CORRECTION' AND NOT EXISTS(SELECT 1 FROM inspection_review_correction_items WHERE review_cycle_id=NEW.id) THEN RAISE EXCEPTION 'return requires correction items'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION correction_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM inspection_review_cycles c JOIN inspections i ON i.id=c.inspection_id JOIN bpm_template_items b ON b.id=NEW.bpm_item_id WHERE c.id=NEW.review_cycle_id AND c.status IN('PENDING_REVIEW','RESUBMITTED') AND b.template_version_id=i.bpm_template_version_id AND b.item_kind='CRITERION' AND b.is_evaluable) THEN RAISE EXCEPTION 'invalid correction item'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION report_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='UPDATE' AND OLD.status='OFFICIAL' THEN RAISE EXCEPTION 'official report immutable'; END IF; IF TG_OP='UPDATE' AND NEW.status='OFFICIAL' AND NOT EXISTS(SELECT 1 FROM inspection_calculations c WHERE c.id=NEW.calculation_id AND c.inspection_id=NEW.inspection_id AND c.is_current) THEN RAISE EXCEPTION 'official report requires current calculation'; END IF; RETURN COALESCE(NEW,OLD); END $$;
CREATE TRIGGER reviews_guard BEFORE INSERT OR UPDATE ON inspection_review_cycles FOR EACH ROW EXECUTE FUNCTION review_guard();
CREATE TRIGGER correction_guard BEFORE INSERT OR UPDATE ON inspection_review_correction_items FOR EACH ROW EXECUTE FUNCTION correction_guard();
CREATE TRIGGER reports_guard BEFORE INSERT OR UPDATE OR DELETE ON inspection_reports FOR EACH ROW EXECUTE FUNCTION report_guard();

CREATE OR REPLACE FUNCTION inspection_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE assignment_case uuid; assignment_evaluator uuid; assignment_active boolean; case_current_status case_status;
BEGIN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'inspections are historical and cannot be deleted' USING ERRCODE='55000'; END IF;
  IF TG_OP='INSERT' THEN SELECT status INTO case_current_status FROM cases WHERE id=NEW.case_id FOR UPDATE; SELECT case_id,evaluator_user_id,is_active INTO assignment_case,assignment_evaluator,assignment_active FROM case_assignments WHERE id=NEW.case_assignment_id FOR UPDATE; IF case_current_status<>'ASSIGNED' OR assignment_case IS DISTINCT FROM NEW.case_id OR assignment_evaluator IS DISTINCT FROM NEW.evaluator_user_id OR assignment_active IS DISTINCT FROM true THEN RAISE EXCEPTION 'inspection assignment invalid' USING ERRCODE='23514'; END IF; IF NOT EXISTS(SELECT 1 FROM bpm_template_versions WHERE id=NEW.bpm_template_version_id AND status='PUBLISHED') OR NOT EXISTS(SELECT 1 FROM risk_rule_versions WHERE id=NEW.risk_rule_version_id AND status='PUBLISHED') THEN RAISE EXCEPTION 'inspection versions must be published' USING ERRCODE='23514'; END IF; RETURN NEW; END IF;
  IF OLD.status='SUBMITTED' THEN RAISE EXCEPTION 'submitted inspection is immutable' USING ERRCODE='55000'; END IF;
  IF NEW.case_id<>OLD.case_id OR NEW.case_assignment_id<>OLD.case_assignment_id OR NEW.evaluator_user_id<>OLD.evaluator_user_id OR NEW.bpm_template_version_id<>OLD.bpm_template_version_id OR NEW.risk_rule_version_id<>OLD.risk_rule_version_id OR NEW.created_by_user_id<>OLD.created_by_user_id THEN RAISE EXCEPTION 'inspection context is immutable' USING ERRCODE='55000'; END IF;
  IF NEW.content_revision<OLD.content_revision OR NEW.content_revision>OLD.content_revision+1 THEN RAISE EXCEPTION 'invalid inspection content revision' USING ERRCODE='23514'; END IF;
  IF NEW.status IS DISTINCT FROM OLD.status AND NOT ((OLD.status='DRAFT' AND NEW.status='IN_PROGRESS') OR (OLD.status='IN_PROGRESS' AND NEW.status='PENDING_SUBMISSION') OR (OLD.status='PENDING_SUBMISSION' AND NEW.status IN('IN_PROGRESS','SUBMITTED'))) THEN RAISE EXCEPTION 'invalid inspection transition' USING ERRCODE='23514'; END IF;
  IF NEW.status IS DISTINCT FROM OLD.status AND NEW.status IN('PENDING_SUBMISSION','SUBMITTED') AND EXISTS(SELECT 1 FROM bpm_template_items item WHERE item.template_version_id=NEW.bpm_template_version_id AND item.item_kind='CRITERION' AND item.is_evaluable AND NOT EXISTS(SELECT 1 FROM inspection_bpm_responses response WHERE response.inspection_id=NEW.id AND response.bpm_item_id=item.id)) THEN RAISE EXCEPTION 'all evaluable BPM items require responses' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION inspection_bpm_response_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE ins inspections%ROWTYPE; item_template uuid; item_kind_value bpm_item_kind; evaluable boolean; iid uuid; BEGIN iid:=COALESCE(NEW.inspection_id,OLD.inspection_id); SELECT * INTO ins FROM inspections WHERE id=iid FOR UPDATE; IF NOT FOUND OR ins.status NOT IN('DRAFT','IN_PROGRESS') THEN RAISE EXCEPTION 'inspection is not editable' USING ERRCODE='23514'; END IF; IF TG_OP IN('INSERT','UPDATE') THEN SELECT template_version_id,item_kind,is_evaluable INTO item_template,item_kind_value,evaluable FROM bpm_template_items WHERE id=NEW.bpm_item_id; IF item_template IS DISTINCT FROM ins.bpm_template_version_id OR item_kind_value<>'CRITERION' OR evaluable IS DISTINCT FROM true THEN RAISE EXCEPTION 'BPM item does not belong to inspection template' USING ERRCODE='23514'; END IF; END IF; RETURN COALESCE(NEW,OLD); END $$;
CREATE OR REPLACE FUNCTION inspection_factor_selection_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE ins inspections%ROWTYPE; factor_rule uuid; option_factor uuid; iid uuid; BEGIN iid:=COALESCE(NEW.inspection_id,OLD.inspection_id); SELECT * INTO ins FROM inspections WHERE id=iid FOR UPDATE; IF NOT FOUND OR ins.status NOT IN('DRAFT','IN_PROGRESS') THEN RAISE EXCEPTION 'inspection is not editable' USING ERRCODE='23514'; END IF; IF TG_OP IN('INSERT','UPDATE') THEN SELECT risk_rule_version_id INTO factor_rule FROM risk_factors WHERE id=NEW.risk_factor_id; SELECT risk_factor_id INTO option_factor FROM risk_factor_options WHERE id=NEW.risk_factor_option_id; IF factor_rule IS DISTINCT FROM ins.risk_rule_version_id OR option_factor IS DISTINCT FROM NEW.risk_factor_id THEN RAISE EXCEPTION 'risk factor selection does not belong to inspection rule' USING ERRCODE='23514'; END IF; END IF; RETURN COALESCE(NEW,OLD); END $$;
CREATE OR REPLACE FUNCTION inspection_food_snapshot_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE ins inspections%ROWTYPE; food_rule uuid; source_category_code varchar(120); source_category_name varchar(300); source_subcategory_name varchar(700); source_microbiological_risk microbiological_risk; source_risk_score smallint; BEGIN IF TG_OP IN('UPDATE','DELETE') THEN RAISE EXCEPTION 'inspection food snapshots are immutable' USING ERRCODE='55000'; END IF; SELECT * INTO ins FROM inspections WHERE id=NEW.inspection_id FOR UPDATE; IF NOT FOUND OR ins.status NOT IN('DRAFT','IN_PROGRESS') THEN RAISE EXCEPTION 'inspection is not editable' USING ERRCODE='23514'; END IF; SELECT c.risk_rule_version_id,c.code,c.name,s.name,s.microbiological_risk,s.risk_score INTO food_rule,source_category_code,source_category_name,source_subcategory_name,source_microbiological_risk,source_risk_score FROM food_risk_subcategories s JOIN food_risk_categories c ON c.id=s.category_id WHERE s.id=NEW.food_risk_subcategory_id; IF food_rule IS DISTINCT FROM ins.risk_rule_version_id OR NEW.category_code_snapshot<>source_category_code OR NEW.category_name_snapshot<>source_category_name OR NEW.subcategory_name_snapshot<>source_subcategory_name OR NEW.microbiological_risk_snapshot IS DISTINCT FROM source_microbiological_risk OR NEW.risk_score_snapshot IS DISTINCT FROM source_risk_score THEN RAISE EXCEPTION 'food snapshot does not match inspection rule' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION case_schedule_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE assignment_case uuid; assignment_active boolean; current_status case_status;
BEGIN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'schedule history cannot be deleted' USING ERRCODE='55000'; END IF;
  IF TG_OP='INSERT' THEN IF NEW.status<>'SCHEDULED' OR NEW.case_assignment_id IS NULL OR NEW.scheduled_start_at<=clock_timestamp() OR NEW.scheduled_end_at<=NEW.scheduled_start_at OR NEW.scheduled_end_at-NEW.scheduled_start_at<interval '15 minutes' OR NEW.scheduled_end_at-NEW.scheduled_start_at>interval '12 hours' OR NEW.timezone<>'America/Santo_Domingo' OR NEW.cancellation_reason IS NOT NULL OR NEW.cancelled_at IS NOT NULL OR NEW.cancelled_by_user_id IS NOT NULL THEN RAISE EXCEPTION 'invalid schedule' USING ERRCODE='23514'; END IF; SELECT status INTO current_status FROM cases WHERE id=NEW.case_id FOR UPDATE; SELECT case_id,is_active INTO assignment_case,assignment_active FROM case_assignments WHERE id=NEW.case_assignment_id; IF current_status<>'ASSIGNED' OR assignment_case IS DISTINCT FROM NEW.case_id OR assignment_active IS DISTINCT FROM true THEN RAISE EXCEPTION 'schedule assignment invalid' USING ERRCODE='23514'; END IF; IF NEW.rescheduled_from_schedule_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM case_schedule_entries WHERE id=NEW.rescheduled_from_schedule_id AND case_id=NEW.case_id AND status='RESCHEDULED') THEN RAISE EXCEPTION 'rescheduled schedule predecessor is invalid' USING ERRCODE='23514'; END IF; RETURN NEW; END IF;
  IF OLD.status<>'SCHEDULED' THEN RAISE EXCEPTION 'inactive schedule is immutable' USING ERRCODE='55000'; END IF; IF NEW.status NOT IN('RESCHEDULED','CANCELLED') THEN RAISE EXCEPTION 'scheduled entry must be closed by reschedule or cancellation' USING ERRCODE='23514'; END IF; IF NEW.case_id IS DISTINCT FROM OLD.case_id OR NEW.case_assignment_id IS DISTINCT FROM OLD.case_assignment_id OR NEW.rescheduled_from_schedule_id IS DISTINCT FROM OLD.rescheduled_from_schedule_id OR NEW.scheduled_start_at IS DISTINCT FROM OLD.scheduled_start_at OR NEW.scheduled_end_at IS DISTINCT FROM OLD.scheduled_end_at OR NEW.timezone IS DISTINCT FROM OLD.timezone OR NEW.scheduled_by_user_id IS DISTINCT FROM OLD.scheduled_by_user_id OR NEW.notes IS DISTINCT FROM OLD.notes THEN RAISE EXCEPTION 'schedule details are immutable' USING ERRCODE='55000'; END IF; RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION close_inspection(p_inspection uuid,p_report uuid,p_actor uuid,p_reason text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE inspection_case uuid; active_assignment uuid; active_schedule uuid; closure_id uuid; normalized_reason text;
BEGIN normalized_reason:=COALESCE(NULLIF(btrim(p_reason),''),'Case closed'); SELECT case_id INTO inspection_case FROM inspections WHERE id=p_inspection FOR UPDATE; IF inspection_case IS NULL THEN RAISE EXCEPTION 'inspection not found' USING ERRCODE='23514'; END IF; PERFORM 1 FROM cases WHERE id=inspection_case FOR UPDATE; IF NOT EXISTS(SELECT 1 FROM inspection_review_cycles WHERE inspection_id=p_inspection AND status='APPROVED') THEN RAISE EXCEPTION 'closure requires approved review' USING ERRCODE='23514'; END IF; IF NOT EXISTS(SELECT 1 FROM inspection_reports WHERE id=p_report AND inspection_id=p_inspection AND status='OFFICIAL') THEN RAISE EXCEPTION 'closure requires official report' USING ERRCODE='23514'; END IF; IF NOT EXISTS(SELECT 1 FROM cases WHERE id=inspection_case AND status='ASSIGNED') THEN RAISE EXCEPTION 'case cannot close' USING ERRCODE='23514'; END IF; SELECT id INTO active_assignment FROM case_assignments WHERE case_id=inspection_case AND is_active FOR UPDATE; IF active_assignment IS NULL THEN RAISE EXCEPTION 'closure requires active assignment' USING ERRCODE='23514'; END IF; SELECT id INTO active_schedule FROM case_schedule_entries WHERE case_id=inspection_case AND status='SCHEDULED' FOR UPDATE; IF active_schedule IS NOT NULL THEN PERFORM set_config('app.actor_user_id',p_actor::text,true); PERFORM set_config('app.schedule_change_reason',normalized_reason,true); UPDATE case_schedule_entries SET status='CANCELLED',cancellation_reason=normalized_reason,cancelled_at=clock_timestamp(),cancelled_by_user_id=p_actor WHERE id=active_schedule; END IF; UPDATE case_assignments SET is_active=false,unassigned_at=clock_timestamp(),unassigned_by_user_id=p_actor,change_reason=normalized_reason WHERE id=active_assignment; UPDATE cases SET status='CLOSED',closed_at=clock_timestamp(),closed_reason=normalized_reason WHERE id=inspection_case AND status='ASSIGNED'; IF NOT FOUND THEN RAISE EXCEPTION 'case cannot close' USING ERRCODE='23514'; END IF; INSERT INTO inspection_closures(inspection_id,case_id,official_report_id,closed_by_user_id,closure_reason) VALUES(p_inspection,inspection_case,p_report,p_actor,normalized_reason) RETURNING id INTO closure_id; RETURN closure_id; END $$;
