import { createHash } from 'node:crypto'; import { readdir, readFile } from 'node:fs/promises'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { Client } from 'pg'; import dotenv from 'dotenv';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../db'), repoRoot=path.resolve(root,'../../..'), dir=path.join(root,'migrations'), lock='ebr-bpm-pwa:migrations:v1';
dotenv.config({path:path.join(repoRoot,'.env')});
type M={v:number;n:string;sql:string;sum:string;legacySum:string;down?:string};
export function safe(url:string,destructive=false){const u=new URL(url), local=['localhost','127.0.0.1','::1','postgres'].includes(u.hostname), env=process.env.DATABASE_ENV??''; if(!['postgres:','postgresql:'].includes(u.protocol)||!env||/prod/i.test(u.hostname+u.pathname+env)||(!local&&process.env.ALLOW_REMOTE_DATABASE!=='true'))throw Error('DATABASE_URL insegura: se bloqueó base remota o de producción.');if(destructive&&(!local||env!=='local'||process.env.DB_ALLOW_DESTRUCTIVE!=='true'))throw Error('Acción destructiva solo con host local, DATABASE_ENV=local y DB_ALLOW_DESTRUCTIVE=true.');}
async function files(){const fs=(await readdir(dir)).filter(x=>/^\d{4}_.+\.up\.sql$/.test(x)).sort(), versions=fs.map(x=>x.slice(0,4));if(new Set(versions).size!==versions.length)throw Error('Versiones de migración duplicadas.');return Promise.all(fs.map(async f=>{const [,v,n]=/^(\d{4})_(.+)\.up\.sql$/.exec(f)! ,sql=await readFile(path.join(dir,f),'utf8');let down;try{down=await readFile(path.join(dir,`${v}_${n}.down.sql`),'utf8')}catch{}const digest=(value:string)=>createHash('sha256').update(value).digest('hex');return {v:+v,n,sql,sum:digest(sql.replace(/\r\n/g,'\n')),legacySum:digest(sql),down}}));}
async function open(url=process.env.DATABASE_URL!){if(!url)throw Error('DATABASE_URL es obligatorio.');safe(url);const c=new Client({connectionString:url});await c.connect();return c;}
async function applied(c:Client){const e=await c.query("SELECT to_regclass('public.schema_migrations') IS NOT NULL ok");if(!e.rows[0].ok)return new Map<number,{n:string;sum:string}>();const r=await c.query('SELECT version,name,checksum_sha256 FROM schema_migrations');return new Map(r.rows.map(x=>[x.version,{n:x.name,sum:x.checksum_sha256.trim()}]));}
export async function migrate(url=process.env.MIGRATION_DATABASE_URL??process.env.DATABASE_URL!){const c=await open(url);try{await c.query('SELECT pg_advisory_lock(hashtext($1))',[lock]);const a=await applied(c);for(const m of await files()){const old=a.get(m.v);if(old&&(old.n!==m.n||![m.sum,m.legacySum].includes(old.sum)))throw Error(`Migración aplicada modificada: ${m.v}_${m.n}`);if(old)continue;await c.query('BEGIN');try{await c.query(m.sql);await c.query('INSERT INTO schema_migrations(version,name,checksum_sha256) VALUES($1,$2,$3)',[m.v,m.n,m.sum]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}}}finally{try{await c.query('SELECT pg_advisory_unlock(hashtext($1))',[lock])}finally{await c.end()}}}
export async function verify(url=process.env.MIGRATION_DATABASE_URL??process.env.DATABASE_URL!){const c=await open(url);try{const a=await applied(c), ms=await files(), known=new Set(ms.map(m=>m.v));for(const v of a.keys())if(!known.has(v))throw Error(`Migración aplicada sin archivo versionado: ${v}`);for(const m of ms){const old=a.get(m.v);if(!old||old.n!==m.n||![m.sum,m.legacySum].includes(old.sum))throw Error(`Migración pendiente o checksum inválido: ${m.v}_${m.n}`)}}finally{await c.end()}}
export async function down(url=process.env.DATABASE_URL!){safe(url,true);const c=await open(url);try{await c.query('SELECT pg_advisory_lock(hashtext($1))',[lock]);const a=await applied(c),v=[...a.keys()].sort((x,y)=>y-x)[0],m=(await files()).find(x=>x.v===v);if(!v)return;if(!m?.down)throw Error(`Sin down: ${v}`);await c.query('BEGIN');try{await c.query(m.down);await c.query('DELETE FROM schema_migrations WHERE version=$1',[v]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}}finally{try{await c.query('SELECT pg_advisory_unlock(hashtext($1))',[lock])}finally{await c.end()}}}
export async function seed(name:string,url=process.env.DATABASE_URL!){const c=await open(url);try{const file=path.join(root,'seeds',name);if(!name.endsWith('.sql')||!file.startsWith(path.join(root,'seeds')))throw Error('Nombre de semilla inválido.');await c.query('BEGIN');try{await c.query(await readFile(file,'utf8'));await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}}finally{await c.end()}}
export async function testConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0002_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testAuditConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0003_audit_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testCatalogConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0004_catalog_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testBpmConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0005_bpm_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testRiskConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0006_risk_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testRequestsConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0008_requests_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testAssignmentsConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0009_assignments_constraints.sql'),'utf8'));await c.query(await readFile(path.join(root,'tests','0010_assignment_trigger_type_fix.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testInspectionsConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{for(const file of['0011_inspections_constraints.sql','0012_inspection_finalization_guard_fix.sql']){await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests',file),'utf8'))}finally{await c.query('ROLLBACK')}}}finally{await c.end()}}
export async function testCalculationsConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0013_calculations_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testReviewsConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0013_calculations_constraints.sql'),'utf8'));await c.query(await readFile(path.join(root,'tests','0014_reviews_constraints.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testIdentityScopeConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0015_user_company_scope.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testOrganizationStatusConstraints(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0017_organization_status.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testUniversalGuard(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0019_universal_administration_guard_fix.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testCompanyRequestGuards(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0020_company_requests_api_guards.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testCompanyRequestIntegrity(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0021_company_request_submission_integrity_fix.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testIntakeCases(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0022_institutional_alerts_complaints_api_guards.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testIntakeDecisionIntegrity(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0023_intake_decision_integrity_fix.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testAssignmentSchedulingApi(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0024_assignment_scheduling_api_guards.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testAssignmentClosureCompatibility(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0025_assignment_closure_compatibility_fix.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testInspectionExecutionCalculations(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0026_inspections_offline_calculations_api_guards.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testReviewsReportsClosureApi(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0026_inspections_offline_calculations_api_guards.sql'),'utf8'));await c.query(await readFile(path.join(root,'tests','0027_reviews_reports_closure_api_guards.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testVersionedDefinitionsAdmin(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{
  // 0028 predates explicit defaults and asserts against the resources it creates.
  // Keep that immutable test valid by marking only its transaction-local fixtures as defaults.
  await c.query(`
    SELECT set_config('app.default_definition_transition','replace',true);
    UPDATE bpm_templates SET is_default=false WHERE is_default;
    UPDATE risk_rule_sets SET is_default=false WHERE is_default;
    CREATE FUNCTION test_0028_bpm_default() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.code='ADMIN_0028_BPM' THEN NEW.is_default=true; END IF; RETURN NEW; END $$;
    CREATE FUNCTION test_0028_risk_default() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.code='ADMIN_0028_RISK' THEN NEW.is_default=true; END IF; RETURN NEW; END $$;
    CREATE TRIGGER test_0028_bpm_default BEFORE INSERT ON bpm_templates FOR EACH ROW EXECUTE FUNCTION test_0028_bpm_default();
    CREATE TRIGGER test_0028_risk_default BEFORE INSERT ON risk_rule_sets FOR EACH ROW EXECUTE FUNCTION test_0028_risk_default();
  `);
  await c.query(await readFile(path.join(root,'tests','0028_versioned_definitions_administration.sql'),'utf8'))
}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testDefaultVersionedDefinitions(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0029_default_versioned_definitions.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testOfficialImports(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0030_official_imports.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testBpmGuidance(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0031_bpm_guidance_hierarchy_fix.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testInspectionLocation(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0026_inspections_offline_calculations_api_guards.sql'),'utf8'));await c.query(await readFile(path.join(root,'tests','0032_inspection_location_capture.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
export async function testEvidenceCriterion(url=process.env.DATABASE_URL!){const c=await open(url);try{await c.query('BEGIN');try{await c.query(await readFile(path.join(root,'tests','0026_inspections_offline_calculations_api_guards.sql'),'utf8'));await c.query(await readFile(path.join(root,'tests','0033_evidence_criterion_link.sql'),'utf8'))}finally{await c.query('ROLLBACK')}}finally{await c.end()}}
