import type{QueryResult,QueryResultRow}from'pg';import type{AssignmentList,ScheduleList}from'./schemas.js';
export type Runner={query:<T extends QueryResultRow>(sql:string,values?:unknown[])=>Promise<QueryResult<T>>};
const assignmentProjection=`SELECT a.id,a.case_id AS "caseId",a.evaluator_user_id AS "evaluatorUserId",eu.full_name AS "evaluatorFullName",a.assigned_by_user_id AS "assignedByUserId",au.full_name AS "assignedByFullName",a.assigned_at AS "assignedAt",a.unassigned_at AS "unassignedAt",a.is_active AS "isActive",a.change_reason AS reason,a.version,c.origin::text,c.status::text,c.priority::text,c.company_id AS "companyId",c.establishment_id AS "establishmentId",EXISTS(SELECT 1 FROM inspections i WHERE i.case_assignment_id=a.id AND i.status IN ('DRAFT','IN_PROGRESS','PENDING_SUBMISSION')) AS "hasEditableInspection" FROM case_assignments a JOIN users eu ON eu.id=a.evaluator_user_id JOIN users au ON au.id=a.assigned_by_user_id JOIN cases c ON c.id=a.case_id`;
const scheduleProjection=`SELECT s.id,s.case_id AS "caseId",s.case_assignment_id AS "assignmentId",a.evaluator_user_id AS "evaluatorUserId",u.full_name AS "evaluatorFullName",s.scheduled_start_at AS "scheduledStartAt",s.scheduled_end_at AS "scheduledEndAt",s.timezone,s.status::text,s.notes,s.cancellation_reason AS "cancellationReason",s.cancelled_at AS "cancelledAt",s.rescheduled_from_schedule_id AS "rescheduledFromScheduleId",s.version FROM case_schedule_entries s JOIN case_assignments a ON a.id=s.case_assignment_id JOIN users u ON u.id=a.evaluator_user_id`;
export async function caseLock(r:Runner,id:string){const q=await r.query<any>('SELECT id,origin::text,status::text,priority::text,company_id AS "companyId",establishment_id AS "establishmentId" FROM cases WHERE id=$1 FOR UPDATE',[id]);return q.rows[0]}
export async function evaluator(r:Runner,id:string){const q=await r.query<any>('SELECT u.id,u.full_name AS "fullName",u.status::text,r.code AS role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=$1',[id]);return q.rows[0]}
export async function assignableEvaluators(r:Runner,page:number,limit:number,search?:string){const pattern=search?`%${search.toLowerCase()}%`:null;const where=" FROM users u JOIN roles r ON r.id=u.role_id WHERE r.code='EVALUATOR' AND u.status='APPROVED' AND ($1::text IS NULL OR lower(u.full_name) LIKE $1)";const count=await r.query<{total:string}>(`SELECT count(*)::text AS total${where}`,[pattern]);const rows=await r.query<{id:string;fullName:string}>(`SELECT u.id,u.full_name AS "fullName"${where} ORDER BY u.full_name,u.id LIMIT $2 OFFSET $3`,[pattern,limit,(page-1)*limit]);return{rows:rows.rows,total:Number(count.rows[0]?.total??0)}}
export async function activeAssignment(r:Runner,caseId:string,lock=false){const q=await r.query<any>(`${assignmentProjection} WHERE a.case_id=$1 AND a.is_active${lock?' FOR UPDATE OF a':''}`,[caseId]);return q.rows[0]}
export async function assignmentById(r:Runner,id:string){const q=await r.query<any>(`${assignmentProjection} WHERE a.id=$1`,[id]);return q.rows[0]}
export async function assignmentHistoryAccess(r:Runner,caseId:string,evaluatorId:string){const q=await r.query('SELECT 1 FROM case_assignments WHERE case_id=$1 AND evaluator_user_id=$2 LIMIT 1',[caseId,evaluatorId]);return Boolean(q.rowCount)}
export async function insertAssignment(r:Runner,caseId:string,evaluatorId:string,actor:string,reason?:string){const q=await r.query<{id:string}>('INSERT INTO case_assignments(case_id,evaluator_user_id,assigned_by_user_id,change_reason) VALUES($1,$2,$3,$4) RETURNING id',[caseId,evaluatorId,actor,reason??null]);return q.rows[0].id}
export async function closeAssignment(r:Runner,id:string,version:number,actor:string,reason:string){const q=await r.query('UPDATE case_assignments SET is_active=false,unassigned_at=clock_timestamp(),unassigned_by_user_id=$1,change_reason=$2 WHERE id=$3 AND version=$4 AND is_active',[actor,reason,id,version]);return Boolean(q.rowCount)}
export async function listAssignments(r:Runner,i:AssignmentList,evaluatorScope?:string,caseScope?:string){const evaluator=evaluatorScope??i.evaluatorUserId??null,caseId=caseScope??i.caseId??null,values=[i.active??null,evaluator,caseId,i.origin??null,i.assignedFrom??null,i.assignedTo??null],where=' WHERE ($1::boolean IS NULL OR a.is_active=$1) AND ($2::uuid IS NULL OR a.evaluator_user_id=$2) AND ($3::uuid IS NULL OR a.case_id=$3) AND ($4::case_origin IS NULL OR c.origin=$4) AND ($5::timestamptz IS NULL OR a.assigned_at>=$5) AND ($6::timestamptz IS NULL OR a.assigned_at<=$6)';const count=await r.query<{total:string}>(`SELECT count(*)::text total FROM case_assignments a JOIN cases c ON c.id=a.case_id${where}`,values);const rows=await r.query<any>(`${assignmentProjection}${where} ORDER BY a.assigned_at DESC LIMIT $7 OFFSET $8`,[...values,i.limit,(i.page-1)*i.limit]);return{rows:rows.rows,total:Number(count.rows[0]?.total??0)}}
export async function activeSchedule(r:Runner,caseId:string,lock=false){const q=await r.query<any>(`${scheduleProjection} WHERE s.case_id=$1 AND s.status='SCHEDULED'${lock?' FOR UPDATE OF s':''}`,[caseId]);return q.rows[0]}
export async function scheduleById(r:Runner,id:string,caseId:string,lock=false){const q=await r.query<any>(`${scheduleProjection} WHERE s.id=$1 AND s.case_id=$2${lock?' FOR UPDATE OF s':''}`,[id,caseId]);return q.rows[0]}
export async function insertSchedule(r:Runner,caseId:string,assignmentId:string,start:string,end:string,actor:string,notes?:string,previous?:string){const q=await r.query<{id:string}>('INSERT INTO case_schedule_entries(case_id,case_assignment_id,rescheduled_from_schedule_id,scheduled_start_at,scheduled_end_at,timezone,scheduled_by_user_id,notes) VALUES($1,$2,$3,$4,$5,\'America/Santo_Domingo\',$6,$7) RETURNING id',[caseId,assignmentId,previous??null,start,end,actor,notes??null]);return q.rows[0].id}
export async function setHistoryContext(r:Runner,actor:string,reason:string){await r.query("SELECT set_config('app.actor_user_id',$1,true),set_config('app.schedule_change_reason',$2,true)",[actor,reason])}
export async function markRescheduled(r:Runner,id:string,version?:number){const values=version===undefined?[id]:[id,version];const q=await r.query(`UPDATE case_schedule_entries SET status='RESCHEDULED' WHERE id=$1 AND status='SCHEDULED'${version===undefined?'':' AND version=$2'}`,values);return Boolean(q.rowCount)}
export async function cancelSchedule(r:Runner,id:string,version:number,actor:string,reason:string){const q=await r.query("UPDATE case_schedule_entries SET status='CANCELLED',cancellation_reason=$1,cancelled_at=clock_timestamp(),cancelled_by_user_id=$2 WHERE id=$3 AND version=$4 AND status='SCHEDULED'",[reason,actor,id,version]);return Boolean(q.rowCount)}
export async function overlaps(r:Runner,evaluatorId:string,start:string,end:string,excludeSchedule?:string,excludeCase?:string){const q=await r.query<{id:string}>('SELECT s.id FROM case_schedule_entries s JOIN case_assignments a ON a.id=s.case_assignment_id WHERE a.evaluator_user_id=$1 AND s.status=\'SCHEDULED\' AND s.scheduled_start_at<$3 AND s.scheduled_end_at>$2 AND ($4::uuid IS NULL OR s.id<>$4) AND ($5::uuid IS NULL OR s.case_id<>$5) ORDER BY s.id',[evaluatorId,start,end,excludeSchedule??null,excludeCase??null]);return q.rows.map(x=>x.id)}
export async function listSchedules(r:Runner,i:ScheduleList,evaluatorScope?:string,caseScope?:string){const evaluator=evaluatorScope??i.evaluatorUserId??null,caseId=caseScope??i.caseId??null,values=[i.status??null,evaluator,caseId,i.startFrom??null,i.startTo??null],where=' WHERE ($1::case_schedule_status IS NULL OR s.status=$1) AND ($2::uuid IS NULL OR a.evaluator_user_id=$2) AND ($3::uuid IS NULL OR s.case_id=$3) AND ($4::timestamptz IS NULL OR s.scheduled_start_at>=$4) AND ($5::timestamptz IS NULL OR s.scheduled_start_at<=$5)';const count=await r.query<{total:string}>(`SELECT count(*)::text total FROM case_schedule_entries s JOIN case_assignments a ON a.id=s.case_assignment_id${where}`,values);const rows=await r.query<any>(`${scheduleProjection}${where} ORDER BY s.scheduled_start_at DESC LIMIT $6 OFFSET $7`,[...values,i.limit,(i.page-1)*i.limit]);return{rows:rows.rows,total:Number(count.rows[0]?.total??0)}}
