import type { QueryResult, QueryResultRow } from 'pg';
import type { ContactInput, LinkContactInput, PatchContactInput } from './schemas.js';
type Runner = { query: <T extends QueryResultRow>(text: string, values?: unknown[]) => Promise<QueryResult<T>> };
export type ContactRow = { id: string; fullName: string; identityDocument: string | null; phone: string | null; email: string | null; version: number; createdAt: Date; updatedAt: Date };
const contactProjection = `SELECT id,full_name AS "fullName",identity_document AS "identityDocument",phone,email,version,created_at AS "createdAt",updated_at AS "updatedAt" FROM contacts`;
const relationProjection = (entity: 'company' | 'establishment') => `SELECT r.id,r.${entity}_id AS "${entity}Id",r.contact_id AS "contactId",r.relationship_type AS "relationshipType",r.is_primary AS "isPrimary",r.effective_from::text AS "effectiveFrom",r.effective_to::text AS "effectiveTo",r.version AS "relationVersion",c.full_name AS "fullName",c.identity_document AS "identityDocument",c.phone,c.email,c.version AS "contactVersion",c.created_at AS "createdAt",c.updated_at AS "updatedAt" FROM ${entity}_contacts r JOIN contacts c ON c.id=r.contact_id`;
export async function findContact(runner: Runner, id: string) { const r = await runner.query<ContactRow>(`${contactProjection} WHERE id=$1`, [id]); return r.rows[0]; }
export async function findContactByDocument(runner: Runner, document: string) { const r = await runner.query<ContactRow>(`${contactProjection} WHERE identity_document_normalized=normalize_identifier($1)`, [document]); return r.rows[0]; }
export async function createContact(runner: Runner, value: ContactInput) { const r = await runner.query<{ id: string }>(`INSERT INTO contacts(full_name,identity_document,phone,email) VALUES($1,$2,$3,$4) RETURNING id`, [value.fullName,value.identityDocument ?? null,value.phone ?? null,value.email ?? null]); return r.rows[0].id; }
export async function updateContact(runner: Runner, id: string, value: PatchContactInput) { const r = await runner.query<QueryResultRow>(`UPDATE contacts SET full_name=COALESCE($1,full_name),identity_document=CASE WHEN $2 THEN $3 ELSE identity_document END,phone=CASE WHEN $4 THEN $5 ELSE phone END,email=CASE WHEN $6 THEN $7 ELSE email END WHERE id=$8 AND version=$9`, [value.fullName ?? null,value.identityDocument !== undefined,value.identityDocument ?? null,value.phone !== undefined,value.phone ?? null,value.email !== undefined,value.email ?? null,id,value.version]); return Boolean(r.rowCount); }
export async function listContacts(runner: Runner, page: number, limit: number, search?: string, companyId?: string) { const p = search ? `%${search.toLowerCase()}%` : null; const where = ` WHERE ($1::text IS NULL OR lower(c.full_name) LIKE $1 OR lower(COALESCE(c.email,'')) LIKE $1) AND ($2::uuid IS NULL OR EXISTS (SELECT 1 FROM company_contacts cc WHERE cc.contact_id=c.id AND cc.company_id=$2) OR EXISTS (SELECT 1 FROM establishment_contacts ec JOIN establishments e ON e.id=ec.establishment_id WHERE ec.contact_id=c.id AND e.company_id=$2))`; const count = await runner.query<{ total: string }>(`SELECT count(*) total FROM contacts c${where}`, [p,companyId ?? null]); const rows = await runner.query<ContactRow>(`${contactProjection} c${where} ORDER BY c.created_at DESC LIMIT $3 OFFSET $4`, [p,companyId ?? null,limit,(page-1)*limit]); return { rows: rows.rows, total: Number(count.rows[0]?.total ?? 0) }; }
export async function contactHasCompanyRelation(runner: Runner, contactId: string, companyId: string) { const r = await runner.query(`SELECT 1 FROM company_contacts WHERE contact_id=$1 AND company_id=$2 UNION ALL SELECT 1 FROM establishment_contacts ec JOIN establishments e ON e.id=ec.establishment_id WHERE ec.contact_id=$1 AND e.company_id=$2 LIMIT 1`, [contactId,companyId]); return Boolean(r.rowCount); }
export async function findCompany(runner: Runner, id: string) { const r = await runner.query<{ id: string; status: string }>(`SELECT id,status::text AS status FROM companies WHERE id=$1`, [id]); return r.rows[0]; }
export async function findEstablishment(runner: Runner, id: string) { const r = await runner.query<{ id: string; companyId: string }>(`SELECT id,company_id AS "companyId" FROM establishments WHERE id=$1`, [id]); return r.rows[0]; }
export async function membershipCompany(runner: Runner, userId: string) { const r = await runner.query<{ companyId: string }>(`SELECT m.company_id AS "companyId" FROM user_company_memberships m JOIN companies c ON c.id=m.company_id WHERE m.user_id=$1 AND m.effective_to IS NULL AND c.status='ACTIVE'`, [userId]); return r.rows[0]?.companyId; }
export async function createRelation(runner: Runner, entity: 'company' | 'establishment', entityId: string, contactId: string, value: LinkContactInput) { const table = entity === 'company' ? 'company_contacts' : 'establishment_contacts'; const column = `${entity}_id`; const r = await runner.query<{ id: string }>(`INSERT INTO ${table}(${column},contact_id,relationship_type,is_primary,effective_from) VALUES($1,$2,$3,$4,$5) RETURNING id`, [entityId,contactId,value.relationshipType,value.isPrimary,value.effectiveFrom]); return r.rows[0].id; }
export async function relation(runner: Runner, entity: 'company' | 'establishment', entityId: string, relationId: string, lock=false) { const table = entity === 'company' ? 'company_contacts' : 'establishment_contacts'; const col = `${entity}_id`; const r = await runner.query<{ id: string; contactId: string; effectiveFrom: string; effectiveTo: string | null; version: number }>(`SELECT id,contact_id AS "contactId",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",version FROM ${table} WHERE id=$1 AND ${col}=$2${lock ? ' FOR UPDATE' : ''}`, [relationId,entityId]); return r.rows[0]; }
export async function endRelation(runner: Runner, entity: 'company' | 'establishment', relationId: string, version: number, effectiveTo: string) { const table = entity === 'company' ? 'company_contacts' : 'establishment_contacts'; const r = await runner.query<QueryResultRow>(`UPDATE ${table} SET effective_to=$1 WHERE id=$2 AND version=$3 AND effective_to IS NULL`, [effectiveTo,relationId,version]); return Boolean(r.rowCount); }
export async function listRelations(runner: Runner, entity: 'company' | 'establishment', entityId: string) { const r = await runner.query(`${relationProjection(entity)} WHERE r.${entity}_id=$1 ORDER BY r.effective_from DESC`, [entityId]); return r.rows; }
