import { Router, type Request, type Response } from 'express';
import { authenticate } from '../../core/auth/authenticate.js';
import { env } from '../../config/env.js';
import { ContactError, create, end, get, link, list, listRelations, patch } from './service.js';
import { createContactSchema,endRelationSchema,idSchema,linkContactSchema,listContactsSchema,patchContactSchema } from './schemas.js';
const router=Router();router.use(authenticate);const ok=(res:Response,data:unknown,extra:object={})=>res.json({data,meta:{correlationId:res.locals.correlationId,...extra}});const fail=(req:Request,res:Response,status:number,code:string,msg:string)=>res.status(status).json({error:{code,message:msg},meta:{correlationId:req.context.correlationId}});
const error=(req:Request,res:Response,e:unknown)=>{if(!(e instanceof ContactError))throw e;const m={FORBIDDEN:[403,'FORBIDDEN','Acceso denegado.'],NOT_FOUND:[404,'NOT_FOUND','Recurso no encontrado.'],CONFLICT:[409,'CONFLICT','La operación entra en conflicto.'],STALE_VERSION:[409,'STALE_VERSION','La versión está desactualizada.'],CONTACT_DATA_MISMATCH:[409,'CONTACT_DATA_MISMATCH','Los datos no coinciden con el contacto existente.']}as const;const [s,c,msg]=m[e.code];return fail(req,res,s,c,msg)};const wrapped=(fn:(q:Request,s:Response)=>Promise<Response|undefined>)=>async(q:Request,s:Response,n:any)=>{try{return await fn(q,s)}catch(e){try{return error(q,s,e)}catch(x){return n(x)}}};const valid=(v:unknown)=>idSchema.safeParse(v);
router.get('/contacts',wrapped(async(q,s)=>{const p=listContactsSchema.safeParse(q.query);if(!p.success)return fail(q,s,400,'VALIDATION_ERROR','Consulta inválida.');const r=await list(p.data.page,p.data.limit,p.data.search,q.auth!);return ok(s,r.rows,{page:p.data.page,limit:p.data.limit,total:r.total})}));
router.post('/contacts',wrapped(async(q,s)=>{const p=createContactSchema.safeParse(q.body);if(!p.success)return fail(q,s,400,'VALIDATION_ERROR','Datos inválidos.');return s.status(201).json({data:await create(p.data,q.auth!,q.context.correlationId),meta:{correlationId:q.context.correlationId}})}));
router.get('/contacts/:id',wrapped(async(q,s)=>{const id=valid(q.params.id);if(!id.success)return fail(q,s,400,'VALIDATION_ERROR','Identificador inválido.');const full=q.auth!.role==='ADMIN'||q.auth!.role==='UNIVERSAL';if(full&&Math.floor(Date.now()/1000)-q.auth!.authTime>env.JWT_REAUTH_MAX_AGE_MINUTES*60)return fail(q,s,401,'REAUTHENTICATION_REQUIRED','Se requiere autenticación reciente.');return ok(s,await get(id.data,q.auth!,full))}));
router.patch('/contacts/:id',wrapped(async(q,s)=>{const id=valid(q.params.id),p=patchContactSchema.safeParse(q.body);if(!id.success||!p.success)return fail(q,s,400,'VALIDATION_ERROR','Datos inválidos.');return ok(s,await patch(id.data,p.data,q.auth!,q.context.correlationId))}));
for(const entity of ['company','establishment'] as const){const base=entity==='company'?'/companies/:entityId/contacts':'/establishments/:entityId/contacts';router.get(base,wrapped(async(q,s)=>{const id=valid(q.params.entityId);if(!id.success)return fail(q,s,400,'VALIDATION_ERROR','Identificador inválido.');return ok(s,await listRelations(entity,id.data,q.auth!))}));router.post(base,wrapped(async(q,s)=>{const id=valid(q.params.entityId),p=linkContactSchema.safeParse(q.body);if(!id.success||!p.success)return fail(q,s,400,'VALIDATION_ERROR','Datos inválidos.');return s.status(201).json({data:await link(entity,id.data,p.data,q.auth!,q.context.correlationId),meta:{correlationId:q.context.correlationId}})}));router.post(`${base}/:relationId/end`,wrapped(async(q,s)=>{const id=valid(q.params.entityId),rel=valid(q.params.relationId),p=endRelationSchema.safeParse(q.body);if(!id.success||!rel.success||!p.success)return fail(q,s,400,'VALIDATION_ERROR','Datos inválidos.');return ok(s,await end(entity,id.data,rel.data,p.data.version,p.data.effectiveTo,q.auth!,q.context.correlationId))}));}
export default router;
