import type { PoolClient } from 'pg';
import { writeDomainAudit } from '../../core/audit/domain-audit.service.js';
import type { RoleCode } from '../../core/auth/roles.js';
import { query, withTransaction } from '../../db/client.js';
import type { ContactInput, LinkContactInput, PatchContactInput } from './schemas.js';
import * as repo from './repository.js';
export class ContactError extends Error { constructor(public readonly code: 'FORBIDDEN'|'NOT_FOUND'|'CONFLICT'|'STALE_VERSION'|'CONTACT_DATA_MISMATCH') { super(code); } }
type Auth={userId:string;role:RoleCode}; const globals=new Set<RoleCode>(['ADMIN','UNIVERSAL','COORDINATOR','EVALUATOR']); const writers=new Set<RoleCode>(['ADMIN','UNIVERSAL']);
const masked=(value:string|null)=>value===null?null:value.length<=4?'*'.repeat(value.length):`${'*'.repeat(Math.max(3,value.length-4))}${value.slice(-4)}`;
const dto=(row:any, full=false)=>({id:row.id,fullName:row.fullName,identityDocumentMasked:masked(row.identityDocument),...(full?{identityDocument:row.identityDocument}:{}),phone:row.phone,email:row.email,version:row.version,createdAt:row.createdAt,updatedAt:row.updatedAt});
const same=(a:string|null|undefined,b:string|null|undefined)=> (a??null)===(b??null);
const normalizedEmail=(value:string|null|undefined)=>value?.trim().toLowerCase()??null;
async function scope(auth:Auth, client?:PoolClient){ if(globals.has(auth.role))return undefined; if(auth.role==='COMPANY_ADMIN'||auth.role==='DELEGATE')return (await repo.membershipCompany(client??{query},auth.userId))??null; throw new ContactError('FORBIDDEN'); }
async function accessEntity(auth:Auth, companyId:string, write:boolean, client?:PoolClient){ if(globals.has(auth.role)){if(write&&!writers.has(auth.role))throw new ContactError('FORBIDDEN');return;} if(auth.role!=='COMPANY_ADMIN'&&auth.role!=='DELEGATE')throw new ContactError('FORBIDDEN');if(write&&auth.role!=='COMPANY_ADMIN')throw new ContactError('FORBIDDEN');if((await scope(auth,client))!==companyId)throw new ContactError('FORBIDDEN'); }
async function entityCompany(entity:'company'|'establishment', id:string, client?:PoolClient){if(entity==='company'){const c=await repo.findCompany(client??{query},id);if(!c)throw new ContactError('NOT_FOUND');return c.id;}const e=await repo.findEstablishment(client??{query},id);if(!e)throw new ContactError('NOT_FOUND');return e.companyId;}
const conflict=(error:any)=>{if(error?.code==='23505'||error?.code==='23P01')throw new ContactError('CONFLICT');throw error;};
export async function list(page:number,limit:number,search:string|undefined,auth:Auth){const s=await scope(auth);if(s===null)return{rows:[],total:0};const r=await repo.listContacts({query},page,limit,search,s);return{rows:r.rows.map(x=>dto(x)),total:r.total};}
export async function get(id:string,auth:Auth,full:boolean){const c=await repo.findContact({query},id);if(!c)throw new ContactError('NOT_FOUND');const s=await scope(auth);if(s!==undefined&&(s===null||!(await repo.contactHasCompanyRelation({query},id,s))))throw new ContactError('FORBIDDEN');return dto(c,full&&writers.has(auth.role));}
export async function create(input:ContactInput,actor:Auth,correlationId:string){if(!writers.has(actor.role))throw new ContactError('FORBIDDEN');try{return await withTransaction(async client=>{const id=await repo.createContact(client,input);await writeDomainAudit({action:'CONTACT_CREATED',actorUserId:actor.userId,correlationId,entityType:'CONTACT',entityId:id,client});return dto((await repo.findContact(client,id))!);});}catch(error){return conflict(error);}}
export async function patch(id:string,input:PatchContactInput,actor:Auth,correlationId:string){if(!writers.has(actor.role))throw new ContactError('FORBIDDEN');try{return await withTransaction(async client=>{if(!await repo.findContact(client,id))throw new ContactError('NOT_FOUND');if(!await repo.updateContact(client,id,input))throw new ContactError('STALE_VERSION');await writeDomainAudit({action:'CONTACT_UPDATED',actorUserId:actor.userId,correlationId,entityType:'CONTACT',entityId:id,client});return dto((await repo.findContact(client,id))!);});}catch(error){return conflict(error);}}
async function resolveContact(client:PoolClient,input:LinkContactInput){if(input.contactId){const c=await repo.findContact(client,input.contactId);if(!c)throw new ContactError('NOT_FOUND');return{contact:c,reused:true};}const value=input.contact!;if(value.identityDocument){const existing=await repo.findContactByDocument(client,value.identityDocument);if(existing){if(!same(existing.fullName,value.fullName)||!same(existing.phone,value.phone)||!same(normalizedEmail(existing.email),normalizedEmail(value.email)))throw new ContactError('CONTACT_DATA_MISMATCH');return{contact:existing,reused:true};}}const id=await repo.createContact(client,value);return{contact:(await repo.findContact(client,id))!,reused:false};}
export async function listRelations(entity:'company'|'establishment',id:string,auth:Auth){const companyId=await entityCompany(entity,id);await accessEntity(auth,companyId,false);return(await repo.listRelations({query},entity,id)).map((row:any)=>({id:row.id,[`${entity}Id`]:row[`${entity}Id`],relationshipType:row.relationshipType,isPrimary:row.isPrimary,effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo,version:row.relationVersion,contact:{...dto(row),version:row.contactVersion}}));}
export async function link(entity:'company'|'establishment',id:string,input:LinkContactInput,actor:Auth,correlationId:string){try{return await withTransaction(async client=>{const companyId=await entityCompany(entity,id,client);await accessEntity(actor,companyId,true,client);const resolved=await resolveContact(client,input);if(input.contactId&&actor.role==='COMPANY_ADMIN'&&!(await repo.contactHasCompanyRelation(client,resolved.contact.id,companyId)))throw new ContactError('FORBIDDEN');if(!resolved.reused)await writeDomainAudit({action:'CONTACT_CREATED',actorUserId:actor.userId,correlationId,entityType:'CONTACT',entityId:resolved.contact.id,client});const relationId=await repo.createRelation(client,entity,id,resolved.contact.id,input);await writeDomainAudit({action:entity==='company'?'COMPANY_CONTACT_LINKED':'ESTABLISHMENT_CONTACT_LINKED',actorUserId:actor.userId,correlationId,entityType:entity==='company'?'COMPANY':'ESTABLISHMENT',entityId:id,metadata:{companyId, ...(entity==='establishment'?{establishmentId:id}:{}),relationshipType:input.relationshipType,isPrimary:input.isPrimary,effectiveFrom:input.effectiveFrom,reusedExistingContact:resolved.reused},client});return{id:relationId,contact:dto(resolved.contact),relationshipType:input.relationshipType,isPrimary:input.isPrimary,effectiveFrom:input.effectiveFrom,effectiveTo:null,version:1};});}catch(error){return conflict(error);}}
export async function end(entity:'company'|'establishment',id:string,relationId:string,version:number,effectiveTo:string,actor:Auth,correlationId:string){try{return await withTransaction(async client=>{const companyId=await entityCompany(entity,id,client);await accessEntity(actor,companyId,true,client);const relation=await repo.relation(client,entity,id,relationId,true);if(!relation)throw new ContactError('NOT_FOUND');if(effectiveTo<=relation.effectiveFrom)throw new ContactError('CONFLICT');if(!await repo.endRelation(client,entity,relationId,version,effectiveTo))throw new ContactError('STALE_VERSION');await writeDomainAudit({action:entity==='company'?'COMPANY_CONTACT_ENDED':'ESTABLISHMENT_CONTACT_ENDED',actorUserId:actor.userId,correlationId,entityType:entity==='company'?'COMPANY':'ESTABLISHMENT',entityId:id,metadata:{companyId,...(entity==='establishment'?{establishmentId:id}:{}),effectiveTo},client});return{ended:true};});}catch(error){return conflict(error);}}
