import type { QueryResult, QueryResultRow } from 'pg';
import type { InspectionListInput } from './schemas.js';

export type Runner = { query:<T extends QueryResultRow>(sql:string, values?:unknown[])=>Promise<QueryResult<T>> };

export const projection = `SELECT i.id,i.case_id AS "caseId",i.case_assignment_id AS "assignmentId",i.evaluator_user_id AS "evaluatorUserId",i.bpm_template_version_id AS "bpmTemplateVersionId",i.risk_rule_version_id AS "riskRuleVersionId",i.status::text,i.started_at AS "startedAt",i.finalized_at AS "finalizedAt",i.submitted_at AS "submittedAt",i.created_by_user_id AS "createdByUserId",i.version,i.content_revision AS "contentRevision",i.created_at AS "createdAt",i.updated_at AS "updatedAt",c.origin::text,c.priority::text,c.establishment_id AS "establishmentId",e.name AS "establishmentName",e.address_text AS "establishmentAddress",co.legal_name AS "companyName" FROM inspections i JOIN cases c ON c.id=i.case_id LEFT JOIN establishments e ON e.id=c.establishment_id LEFT JOIN companies co ON co.id=c.company_id`;

export async function inspection(r:Runner,id:string,lock=false){const q=await r.query<any>(`${projection} WHERE i.id=$1${lock?' FOR UPDATE OF i':''}`,[id]);return q.rows[0]}
export async function list(r:Runner,input:InspectionListInput,evaluatorScope?:string){const values=[input.status??null,evaluatorScope??input.evaluatorUserId??null,input.caseId??null,input.origin??null,input.createdFrom??null,input.createdTo??null];const where=` WHERE ($1::inspection_status IS NULL OR i.status=$1) AND ($2::uuid IS NULL OR i.evaluator_user_id=$2) AND ($3::uuid IS NULL OR i.case_id=$3) AND ($4::case_origin IS NULL OR c.origin=$4) AND ($5::timestamptz IS NULL OR i.created_at>=$5) AND ($6::timestamptz IS NULL OR i.created_at<=$6)`;const count=await r.query<{total:string}>(`SELECT count(*)::text total FROM inspections i JOIN cases c ON c.id=i.case_id${where}`,values);const rows=await r.query<any>(`${projection}${where} ORDER BY i.created_at DESC,i.id DESC LIMIT $7 OFFSET $8`,[...values,input.limit,(input.page-1)*input.limit]);return{rows:rows.rows,total:Number(count.rows[0]?.total??0)}}
export async function activeAssignmentForCreate(r:Runner,caseId:string){const q=await r.query<any>(`SELECT c.id AS "caseId",c.status::text,a.id AS "assignmentId",a.evaluator_user_id AS "evaluatorUserId" FROM cases c JOIN case_assignments a ON a.case_id=c.id AND a.is_active WHERE c.id=$1 FOR UPDATE OF c,a`,[caseId]);return q.rows[0]}
export async function latestVersions(r:Runner){const bpm=await r.query<{id:string}>('SELECT effective_bpm_template_version(clock_timestamp()) id');const risk=await r.query<{id:string}>('SELECT effective_risk_rule_version(clock_timestamp()) id');return{bpm:bpm.rows[0]?.id,risk:risk.rows[0]?.id}}
export async function insertInspection(r:Runner,caseId:string,assignmentId:string,evaluator:string,bpm:string,risk:string,createdBy:string=evaluator){const q=await r.query<{id:string}>('INSERT INTO inspections(case_id,case_assignment_id,evaluator_user_id,bpm_template_version_id,risk_rule_version_id,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[caseId,assignmentId,evaluator,bpm,risk,createdBy]);return q.rows[0].id}
export async function editableInspection(r:Runner,caseId:string){const q=await r.query<{id:string}>('SELECT id FROM inspections WHERE case_id=$1 AND status IN(\'DRAFT\',\'IN_PROGRESS\',\'PENDING_SUBMISSION\') LIMIT 1',[caseId]);return q.rows[0]?.id}

export async function responses(r:Runner,id:string){const q=await r.query<any>('SELECT id,bpm_item_id AS "bpmItemId",response_value::text AS "responseValue",observations,version,created_at AS "createdAt",updated_at AS "updatedAt" FROM inspection_bpm_responses WHERE inspection_id=$1 ORDER BY bpm_item_id',[id]);return q.rows}
export async function factors(r:Runner,id:string){const q=await r.query<any>('SELECT s.id,s.risk_factor_id AS "riskFactorId",s.risk_factor_option_id AS "optionId",f.code AS "factorCode",o.code AS "optionCode",o.label AS "optionLabel",o.score, s.version FROM inspection_risk_factor_selections s JOIN risk_factors f ON f.id=s.risk_factor_id JOIN risk_factor_options o ON o.id=s.risk_factor_option_id WHERE s.inspection_id=$1 ORDER BY f.sort_order',[id]);return q.rows}
export async function foods(r:Runner,id:string){const q=await r.query<any>('SELECT id,food_risk_subcategory_id AS "foodRiskSubcategoryId",category_code_snapshot AS "categoryCode",category_name_snapshot AS "categoryName",subcategory_name_snapshot AS "subcategoryName",microbiological_risk_snapshot::text AS "microbiologicalRisk",risk_score_snapshot AS "riskScore",created_at AS "createdAt" FROM inspection_food_snapshots WHERE inspection_id=$1 ORDER BY created_at,id',[id]);return q.rows}
export async function evidence(r:Runner,id:string,evidenceId?:string,lock=false,includePath=false){const fields=`id,inspection_id AS "inspectionId",bpm_item_id AS "bpmItemId",${includePath?'storage_path AS "storagePath",':''}original_file_name AS "fileName",mime_type AS "mimeType",size_bytes AS "sizeBytes",status::text,uploaded_by_user_id AS "uploadedByUserId",validated_at AS "validatedAt",validated_by_user_id AS "validatedByUserId",rejection_reason AS "rejectionReason",archived_at AS "archivedAt",deleted_at AS "deletedAt",version,created_at AS "createdAt",updated_at AS "updatedAt"`;const q=await r.query<any>(`SELECT ${fields} FROM inspection_evidence WHERE inspection_id=$1${evidenceId?' AND id=$2':''} ORDER BY created_at DESC${lock?' FOR UPDATE':''}`,evidenceId?[id,evidenceId]:[id]);return evidenceId?q.rows[0]:q.rows}
export async function currentCalculation(r:Runner,id:string){const q=await r.query<any>('SELECT id,calculation_number AS "calculationNumber",status::text,is_current AS "isCurrent",inspection_content_revision AS "contentRevision",bpm_numerator AS "bpmNumerator",bpm_denominator AS "bpmDenominator",bpm_percentage AS "bpmPercentage",product_risk_score AS "productRiskScore",establishment_risk_score AS "establishmentRiskScore",total_risk_score AS "totalRiskScore",frequency::text,calculated_by_user_id AS "calculatedByUserId",calculated_at AS "calculatedAt" FROM inspection_calculations WHERE inspection_id=$1 AND is_current',[id]);return q.rows[0]}
export async function calculations(r:Runner,id:string){const q=await r.query<any>('SELECT id,calculation_number AS "calculationNumber",status::text,is_current AS "isCurrent",inspection_content_revision AS "contentRevision",bpm_percentage AS "bpmPercentage",product_risk_score AS "productRiskScore",establishment_risk_score AS "establishmentRiskScore",total_risk_score AS "totalRiskScore",frequency::text,calculated_at AS "calculatedAt" FROM inspection_calculations WHERE inspection_id=$1 ORDER BY calculation_number DESC',[id]);return q.rows}
export async function calculationDetail(r:Runner,id:string,calcId:string){const q=await r.query<any>('SELECT id,inspection_id AS "inspectionId",calculation_number AS "calculationNumber",status::text,is_current AS "isCurrent",inspection_content_revision AS "contentRevision",bpm_template_version_id AS "bpmTemplateVersionId",risk_rule_version_id AS "riskRuleVersionId",bpm_numerator AS "bpmNumerator",bpm_denominator AS "bpmDenominator",bpm_percentage AS "bpmPercentage",product_risk_score AS "productRiskScore",establishment_risk_score AS "establishmentRiskScore",total_risk_score AS "totalRiskScore",frequency::text,frequency_range_id AS "frequencyRangeId",calculated_by_user_id AS "calculatedByUserId",calculated_at AS "calculatedAt" FROM inspection_calculations WHERE inspection_id=$1 AND id=$2',[id,calcId]);if(!q.rows[0])return undefined;const [bpm,factors,food,frequency]=await Promise.all([r.query<any>('SELECT bpm_item_id AS "bpmItemId",display_code_snapshot AS "displayCode",response_value::text AS "responseValue",response_score AS "responseScore",is_applicable AS "isApplicable" FROM inspection_calculation_bpm_snapshots WHERE calculation_id=$1 ORDER BY bpm_item_id',[calcId]),r.query<any>('SELECT risk_factor_id AS "riskFactorId",factor_code_snapshot AS "factorCode",factor_name_snapshot AS "factorName",weight_snapshot AS weight,risk_factor_option_id AS "optionId",option_code_snapshot AS "optionCode",option_label_snapshot AS "optionLabel",selected_score_snapshot AS "selectedScore",weighted_contribution AS "weightedContribution",sort_order_snapshot AS "sortOrder" FROM inspection_calculation_factor_snapshots WHERE calculation_id=$1 ORDER BY sort_order_snapshot',[calcId]),r.query<any>('SELECT food_risk_subcategory_id AS "foodRiskSubcategoryId",category_code_snapshot AS "categoryCode",subcategory_name_snapshot AS "subcategoryName",microbiological_risk_snapshot::text AS "microbiologicalRisk",risk_score_snapshot AS "riskScore",is_applicable AS "isApplicable" FROM inspection_calculation_food_snapshots WHERE calculation_id=$1 ORDER BY id',[calcId]),r.query<any>('SELECT lower_bound_snapshot AS "lowerBound",upper_bound_snapshot AS "upperBound",lower_inclusive_snapshot AS "lowerInclusive",upper_inclusive_snapshot AS "upperInclusive",frequency::text,label_snapshot AS label FROM inspection_calculation_frequency_snapshots WHERE calculation_id=$1',[calcId])]);return{...q.rows[0],snapshots:{bpm:bpm.rows,factors:factors.rows,food:food.rows,frequency:frequency.rows[0]}}}
