import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Box, Button, Card, CardContent, FormControl, InputLabel, MenuItem, Select, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material';
import type { AnalyticsEvaluation, AnalyticsLifecycleStatus, RiskLevel } from '@ebr-bpm/core-client';
import { servicioAnalitica } from '../servicios/analitica';
import { EstadoChip, RiesgoChip } from '../componentes/EstadoChip';
import { Cargando, ErrorVista, Vacio } from '../componentes/EstadoVista';
import { etiquetasEstado, formatearFecha } from '../utilidades/formato';

const states: AnalyticsLifecycleStatus[] = ['READY_FOR_REVIEW', 'PENDING_REVIEW', 'RETURNED_FOR_CORRECTION', 'RESUBMITTED', 'APPROVED', 'CLOSED', 'DRAFT', 'IN_PROGRESS', 'PENDING_SUBMISSION'];
export function Evaluaciones() {
  const [search, setSearch] = useState(''); const [state, setState] = useState<AnalyticsLifecycleStatus | ''>(''); const [risk, setRisk] = useState<RiskLevel | ''>('');
  const [page, setPage] = useState(0); const [limit, setLimit] = useState(20); const [items, setItems] = useState<AnalyticsEvaluation[]>(); const [total, setTotal] = useState(0); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); try { const result = await servicioAnalitica.listarEvaluaciones({ page: page + 1, limit, search: search || undefined, lifecycleStatus: state || undefined, riskLevel: risk || undefined }); setItems(result.data); setTotal(result.meta.total ?? 0); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudieron cargar las evaluaciones.'); } }, [page, limit, search, state, risk]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  return <Box sx={{ display: 'grid', gap: 3 }}><Box><Typography variant="h1">Evaluaciones</Typography><Typography color="text.secondary">Historial paginado y resultados vigentes del Core.</Typography></Box><Card><CardContent sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '2fr 1fr 1fr' }, gap: 2 }}><TextField label="Empresa, establecimiento, evaluador o UUID" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} /><FormControl><InputLabel>Estado</InputLabel><Select label="Estado" value={state} onChange={(event) => { setState(event.target.value as AnalyticsLifecycleStatus | ''); setPage(0); }}><MenuItem value="">Todos</MenuItem>{states.map((value) => <MenuItem key={value} value={value}>{etiquetasEstado[value]}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Riesgo</InputLabel><Select label="Riesgo" value={risk} onChange={(event) => { setRisk(event.target.value as RiskLevel | ''); setPage(0); }}><MenuItem value="">Todos</MenuItem><MenuItem value="LOW">Bajo</MenuItem><MenuItem value="MEDIUM">Medio</MenuItem><MenuItem value="HIGH">Alto</MenuItem></Select></FormControl></CardContent></Card>{error ? <ErrorVista mensaje={error} /> : !items ? <Cargando /> : <Card><TableContainer><Table><TableHead><TableRow><TableCell>Evaluación</TableCell><TableCell>Empresa y establecimiento</TableCell><TableCell>Inspección</TableCell><TableCell>Estado</TableCell><TableCell>Resultado</TableCell><TableCell align="right">Acción</TableCell></TableRow></TableHead><TableBody>{items.map((item) => <TableRow key={item.id} hover><TableCell><Typography variant="body2" sx={{ fontWeight: 700 }}>{item.id.slice(0, 8)}</Typography><Typography variant="caption" color="text.secondary">{item.evaluatorName}</Typography></TableCell><TableCell><Typography variant="body2">{item.companyTradeName || item.companyName || 'Sin empresa'}</Typography><Typography variant="caption" color="text.secondary">{item.establishmentName || 'Sin establecimiento'}</Typography></TableCell><TableCell>{formatearFecha(item.startedAt || item.createdAt)}</TableCell><TableCell><EstadoChip estado={item.lifecycleStatus} /></TableCell><TableCell>{item.riskLevel ? <RiesgoChip nivel={item.riskLevel} /> : 'Sin cálculo vigente'}</TableCell><TableCell align="right"><Button component={Link} to={`/evaluaciones/${item.id}`} size="small">Abrir</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>{items.length === 0 && <Vacio titulo="Sin resultados" detalle="Ajuste los filtros para encontrar evaluaciones." />}<TablePagination component="div" count={total} page={page} onPageChange={(_event, next) => setPage(next)} rowsPerPage={limit} onRowsPerPageChange={(event) => { setLimit(Number(event.target.value)); setPage(0); }} rowsPerPageOptions={[10, 20, 50, 100]} labelRowsPerPage="Filas por página" /></Card>}</Box>;
}
