import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Box, Button, Card, CardContent, Checkbox, FormControlLabel, Radio, RadioGroup, TextField, Typography } from '@mui/material';
import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded';
import SaveRoundedIcon from '@mui/icons-material/SaveRounded';
import { core } from '../api/core';
import { useAutenticacion } from '../contexto/Autenticacion';
import { servicioAnalitica, type DetalleAnalitico } from '../servicios/analitica';
import { Cargando, ErrorVista } from '../componentes/EstadoVista';

export function Revision() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { canOperate, runAuthorized } = useAutenticacion();
  const [detail, setDetail] = useState<DetalleAnalitico>(); const [decision, setDecision] = useState<'APPROVE' | 'RETURN'>('APPROVE'); const [comment, setComment] = useState(''); const [selected, setSelected] = useState<Set<string>>(new Set()); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { servicioAnalitica.obtenerDetalle(id).then(setDetail).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'No se pudo cargar la revisión.')); }, [id]);
  const criteria = useMemo(() => detail?.workPackage.bpmTemplate.items.filter((item) => item.isEvaluable) ?? [], [detail]);
  const responses = useMemo(() => new Map(detail?.workPackage.responses.map((response) => [response.bpmItemId, response])), [detail]);
  const toggle = (itemId: string) => setSelected((current) => { const next = new Set(current); if (next.has(itemId)) next.delete(itemId); else next.add(itemId); return next; });
  const save = async () => { if (!detail?.review) return; if (decision === 'RETURN' && (!comment.trim() || selected.size === 0)) { setError('La devolución requiere motivo y al menos un criterio.'); return; } setSaving(true); setError(''); try { await runAuthorized(() => decision === 'APPROVE' ? core.approveReview(id, detail.review!.id, comment.trim() || undefined) : core.returnReview(id, detail.review!.id, comment.trim(), [...selected])); navigate(`/evaluaciones/${id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo registrar la decisión.'); } finally { setSaving(false); } };
  if (!detail && error) return <ErrorVista mensaje={error} />; if (!detail) return <Cargando />;
  if (!canOperate) return <Alert severity="info">ADMIN dispone únicamente de consulta. Regrese al detalle para revisar la información.</Alert>;
  if (!detail.review || !['PENDING_REVIEW', 'RESUBMITTED'].includes(detail.review.status)) return <Alert severity="warning">Esta evaluación no tiene una revisión operable.</Alert>;
  return <Box sx={{ display: 'grid', gap: 3 }}><Box><Button component={Link} to={`/evaluaciones/${id}`} startIcon={<ArrowBackRoundedIcon />}>Volver al resultado</Button><Typography variant="h1" sx={{ mt: 1 }}>Revisión {id.slice(0, 8)}</Typography><Typography color="text.secondary">El Core registrará la decisión y limitará una devolución a los criterios seleccionados.</Typography></Box>{error && <Alert severity="error">{error}</Alert>}<Card><CardContent><Typography variant="h2">Decisión</Typography><RadioGroup row value={decision} onChange={(event) => { setDecision(event.target.value as 'APPROVE' | 'RETURN'); if (event.target.value === 'APPROVE') setSelected(new Set()); }}><FormControlLabel value="APPROVE" control={<Radio />} label="Aprobar" /><FormControlLabel value="RETURN" control={<Radio />} label="Devolver para corrección" /></RadioGroup><TextField fullWidth multiline minRows={3} label={decision === 'RETURN' ? 'Motivo obligatorio' : 'Nota opcional'} value={comment} onChange={(event) => setComment(event.target.value)} sx={{ mt: 2 }} /></CardContent></Card>{decision === 'RETURN' && <Card><CardContent><Typography variant="h2">Criterios habilitados para corrección</Typography><Typography color="text.secondary" sx={{ my: 1 }}>Seleccione únicamente los criterios que el evaluador deberá corregir.</Typography><Box sx={{ display: 'grid', gap: 1 }}>{criteria.map((item) => { const response = responses.get(item.id); return <Box key={item.id} sx={{ display: 'flex', gap: 1, alignItems: 'flex-start', p: 1.5, border: '1px solid #d9e3e6', borderRadius: 2 }}><Checkbox checked={selected.has(item.id)} onChange={() => toggle(item.id)} slotProps={{ input: { 'aria-label': `Seleccionar ${item.displayCode || item.title}` } }} /><Box><Typography sx={{ fontWeight: 700 }}>{item.displayCode || 'Criterio'} · {item.title}</Typography><Typography variant="body2" color="text.secondary">Respuesta: {response?.responseValue || 'Sin respuesta'} · Criticidad: {item.criticality || 'No indicada'}</Typography>{response?.observations && <Typography variant="body2">{response.observations}</Typography>}</Box></Box>; })}</Box></CardContent></Card>}<Box sx={{ display: 'flex', justifyContent: 'flex-end' }}><Button variant="contained" startIcon={<SaveRoundedIcon />} disabled={saving} onClick={() => void save()}>{saving ? 'Guardando…' : 'Registrar decisión'}</Button></Box></Box>;
}
