const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(character)=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[character]!);
const cell=(value:unknown)=>`<td>${escapeHtml(value)}</td>`;
export type ReportData={verificationId:string;generatedAt:string;case:{id:string;origin:string;company?:string;establishment?:string};inspection:{id:string;date:string;evaluator:string;approver:string;bpmTemplate:string;riskRule:string};calculation:{bpmPercentage:unknown;productRiskScore:unknown;establishmentRiskScore:unknown;totalRiskScore:unknown;frequency:string};bpm:Array<{code?:string;value:string;applicable:boolean}>;factors:Array<{code:string;name:string;weight:unknown;score:unknown;contribution:unknown}>;evidence:Array<{id:string;mimeType:string;sizeBytes:unknown;status:string}>;history:Array<{eventType:string;occurredAt:string}>};
export function buildOfficialReportHtml(data:ReportData){
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#17202a}h1{font-size:20px;margin:0 0 4px}h2{font-size:14px;margin:18px 0 6px;border-bottom:1px solid #85929e;padding-bottom:3px}.meta{color:#566573}.grid{display:grid;grid-template-columns:1fr 1fr;gap:5px 18px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #aeb6bf;padding:4px;text-align:left}th{background:#eaecee}.score{font-size:13px;font-weight:bold}.footer{margin-top:18px;font-size:9px;color:#566573}</style></head><body>
  <h1>Informe oficial de inspección</h1><div class="meta">Verificación: ${escapeHtml(data.verificationId)} · Generado: ${escapeHtml(data.generatedAt)}</div>
  <h2>Identificación</h2><div class="grid"><div>Caso: ${escapeHtml(data.case.id)}</div><div>Origen: ${escapeHtml(data.case.origin)}</div><div>Empresa: ${escapeHtml(data.case.company||'No aplica')}</div><div>Establecimiento: ${escapeHtml(data.case.establishment||'No aplica')}</div><div>Inspección: ${escapeHtml(data.inspection.id)}</div><div>Fecha: ${escapeHtml(data.inspection.date)}</div><div>Evaluador: ${escapeHtml(data.inspection.evaluator)}</div><div>Coordinador aprobador: ${escapeHtml(data.inspection.approver)}</div><div>Plantilla BPM: ${escapeHtml(data.inspection.bpmTemplate)}</div><div>Regla de riesgo: ${escapeHtml(data.inspection.riskRule)}</div></div>
  <h2>Resumen BPM</h2><table><thead><tr><th>Criterio</th><th>Respuesta</th><th>Aplicable</th></tr></thead><tbody>${data.bpm.map(x=>`<tr>${cell(x.code||'—')}${cell(x.value)}${cell(x.applicable?'Sí':'No')}</tr>`).join('')}</tbody></table>
  <h2>Factores de riesgo</h2><table><thead><tr><th>Código</th><th>Factor</th><th>Peso</th><th>Puntaje</th><th>Contribución</th></tr></thead><tbody>${data.factors.map(x=>`<tr>${cell(x.code)}${cell(x.name)}${cell(x.weight)}${cell(x.score)}${cell(x.contribution)}</tr>`).join('')}</tbody></table>
  <h2>Resultados</h2><div class="grid score"><div>BPM: ${escapeHtml(data.calculation.bpmPercentage)}%</div><div>Riesgo producto: ${escapeHtml(data.calculation.productRiskScore)}</div><div>Riesgo establecimiento: ${escapeHtml(data.calculation.establishmentRiskScore)}</div><div>Riesgo total: ${escapeHtml(data.calculation.totalRiskScore)}</div><div>Frecuencia: ${escapeHtml(data.calculation.frequency)}</div></div>
  <h2>Evidencias autorizadas</h2><table><thead><tr><th>Identificador</th><th>MIME</th><th>Tamaño</th><th>Estado</th></tr></thead><tbody>${data.evidence.map(x=>`<tr>${cell(x.id)}${cell(x.mimeType)}${cell(x.sizeBytes)}${cell(x.status)}</tr>`).join('')}</tbody></table>
  <h2>Historial de revisión</h2><table><thead><tr><th>Evento</th><th>Fecha</th></tr></thead><tbody>${data.history.map(x=>`<tr>${cell(x.eventType)}${cell(x.occurredAt)}</tr>`).join('')}</tbody></table>
  <div class="footer">Documento generado por EBR/BPM. No contiene enlaces de Storage, secretos ni datos personales de contacto.</div></body></html>`;
}
export { escapeHtml };
