import { readFileSync } from 'node:fs';

const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(character)=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[character]!);
const logo=`data:image/jpeg;base64,${readFileSync(new URL('../../../assets/sira-imagotipo.jpeg',import.meta.url)).toString('base64')}`;
const number=(value:unknown,digits=2)=>{const n=Number(value);return Number.isFinite(n)?n.toLocaleString('es-DO',{maximumFractionDigits:digits}):'—'};
const date=(value:unknown)=>{const d=new Date(String(value??''));return Number.isNaN(d.getTime())?'—':d.toLocaleString('es-DO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Santo_Domingo'})};
const frequency:Record<string,string>={ANNUAL:'Anual',SEMIANNUAL:'Semestral',QUARTERLY:'Trimestral',MONTHLY:'Mensual'};
const origin:Record<string,string>={PUBLIC_COMPLAINT:'Denuncia ciudadana',COMPLAINT:'Denuncia ciudadana',SANITARY_ALERT:'Alerta sanitaria',LAPCH_ALERT:'Alerta LAPCH',INSTITUTIONAL_PROGRAM:'Programa institucional',BPM_REQUEST:'Solicitud BPM'};
const response:Record<string,string>={C:'Cumple',CP:'Cumple parcialmente',IT:'Incumple',NA:'No aplica'};
const productRisk:Record<number,string>={1:'Bajo',2:'Medio',3:'Alto'};
const event:Record<string,string>={OPENED:'Revisión iniciada',RETURNED_FOR_CORRECTION:'Devuelta para corrección',RESUBMITTED:'Correcciones reenviadas',APPROVED:'Revisión aprobada'};
const row=(cells:unknown[])=>`<tr>${cells.map(cell=>`<td>${escapeHtml(cell)}</td>`).join('')}</tr>`;

export type ReportData={verificationId:string;generatedAt:string;case:{id:string;origin:string;company?:string;establishment?:string};inspection:{id:string;date:string;evaluator:string;approver:string;bpmTemplate:string;riskRule:string};calculation:{bpmPercentage:unknown;productRiskScore:unknown;establishmentRiskScore:unknown;totalRiskScore:unknown;frequency:string};bpm:Array<{code?:string;title?:string;value:string;applicable:boolean;observations?:string|null}>;factors:Array<{code:string;name:string;selectedLabel?:string;weight:unknown;score:unknown;contribution:unknown}>;evidence:Array<{id:string;fileName:string;criterionCode?:string|null;mimeType:string;sizeBytes:unknown;status:string;storagePath?:string;imageDataUrl?:string}>;history:Array<{eventType:string;occurredAt:string}>;narrative:{executiveSummary:string;additionalFindings:string;recommendations:string};contentVersion:number};

export function buildReportHtml(data:ReportData,status:'DRAFT'|'OFFICIAL'){
  const draft=status==='DRAFT',bpm=Math.max(0,Math.min(100,Number(data.calculation.bpmPercentage)||0));
  const findings=data.bpm.filter(item=>item.value==='IT'||item.value==='CP');
  const nonconformities=data.bpm.filter(item=>item.value==='IT');
  const narrative=(value:string,fallback:string)=>value.trim()?`<p class="narrative">${escapeHtml(value).replace(/\n/g,'<br>')}</p>`:`<p class="empty">${fallback}</p>`;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
    @page{size:A4;margin:15mm 15mm 18mm}*{box-sizing:border-box}body{font:11px Arial,Helvetica,sans-serif;color:#451a03;margin:0;line-height:1.4}
    h1{font-size:22px;line-height:1.15;margin:18px 0 5px;color:#451a03}h2{font-size:13px;margin:23px 0 9px;color:#78350f;border-left:4px solid #d97706;padding:5px 9px;background:#fffbeb}
    .masthead{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #d97706;padding-bottom:12px}.brand{width:180px;height:88px;object-fit:contain;object-position:left center}.masthead-note{text-align:right;color:#92400e;font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:700}
    .eyebrow{color:#92400e;text-transform:uppercase;letter-spacing:.12em;font-weight:700;font-size:9px}.subtitle{color:#92400e;margin-bottom:15px}.status{display:inline-block;padding:4px 9px;border-radius:20px;font-size:9px;font-weight:700;background:${draft?'#fef3c7':'#dcfce7'};color:${draft?'#92400e':'#166534'};margin:6px 0}
    .watermark{position:fixed;top:42%;left:4%;width:92%;text-align:center;color:rgba(120,53,15,.20);font-size:44px;font-weight:800;letter-spacing:.04em;transform:rotate(-30deg);pointer-events:none;z-index:10;white-space:nowrap}
    .intro{display:grid;grid-template-columns:1fr 1fr;gap:8px 20px;background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:13px}.intro-label,.metric-label{display:block;color:#92400e;font-size:9px;text-transform:uppercase;letter-spacing:.05em}.intro-value{font-weight:700;overflow-wrap:anywhere}
    .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metric{background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:10px;min-height:61px;break-inside:avoid}.metric strong{display:block;font-size:17px;color:#78350f;margin-top:3px}.metric.primary{background:#78350f;border-color:#78350f}.metric.primary .metric-label,.metric.primary strong{color:white}.progress{height:8px;background:#fde68a;border-radius:20px;overflow:hidden;margin-top:12px}.progress span{display:block;height:100%;background:#d97706;width:${bpm}%}
    table{width:100%;border-collapse:collapse;font-size:9px;table-layout:fixed}thead{display:table-header-group}tr{break-inside:avoid}th{background:#78350f;color:white;text-align:left;padding:7px 6px}td{padding:6px;border-bottom:1px solid #fde68a;overflow-wrap:anywhere}tbody tr:nth-child(even){background:#fffbeb}.empty{color:#92400e;font-style:italic;padding:8px 0}
    .signature-area{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:18px;break-inside:avoid}.signature{border:1px solid #fde68a;border-radius:8px;padding:12px;height:102px;display:flex;flex-direction:column;justify-content:end}.signature-line{border-top:1px solid #78350f;padding-top:7px}.small{font-size:9px;color:#92400e}.footer{border-top:1px solid #fde68a;margin-top:25px;padding-top:9px;font-size:8px;color:#92400e;overflow-wrap:anywhere}.narrative{white-space:normal;line-height:1.55}.photo{break-inside:avoid;margin:12px 0;padding:9px;border:1px solid #fde68a;border-radius:8px}.photo img{max-width:100%;max-height:150mm;object-fit:contain}.photo figcaption{margin-top:6px;color:#78350f;font-size:9px}
  </style></head><body>
  ${draft?'<div class="watermark" aria-hidden="true">INFORME NO OFICIAL</div>':''}
  <header class="masthead"><img class="brand" src="${logo}" alt="SIRA Tech"><div class="masthead-note">Evaluación sanitaria<br>Inspección BPM / EBR</div></header>
  <div class="eyebrow">Informe de inspección</div><h1>${draft?'Informe no oficial':'Informe oficial'}</h1>
  <div class="subtitle">${escapeHtml(data.case.company||'Sin empresa asociada')} · ${escapeHtml(data.case.establishment||'Sin establecimiento asociado')}</div>
  <div class="status">${draft?'BORRADOR · NO OFICIAL':'INFORME OFICIAL'}</div>
  <h2>Datos de la inspección</h2><div class="intro">
    <div><span class="intro-label">Empresa</span><span class="intro-value">${escapeHtml(data.case.company||'No aplica')}</span></div><div><span class="intro-label">Establecimiento</span><span class="intro-value">${escapeHtml(data.case.establishment||'No aplica')}</span></div>
    <div><span class="intro-label">Origen del caso</span><span class="intro-value">${escapeHtml(origin[data.case.origin]||data.case.origin)}</span></div><div><span class="intro-label">Fecha de inspección</span><span class="intro-value">${date(data.inspection.date)}</span></div>
    <div><span class="intro-label">Evaluador</span><span class="intro-value">${escapeHtml(data.inspection.evaluator)}</span></div><div><span class="intro-label">Revisión aprobada por</span><span class="intro-value">${escapeHtml(data.inspection.approver)}</span></div>
    <div><span class="intro-label">Plantilla BPM</span><span class="intro-value">${escapeHtml(data.inspection.bpmTemplate)}</span></div><div><span class="intro-label">Reglas de riesgo</span><span class="intro-value">${escapeHtml(data.inspection.riskRule)}</span></div>
  </div>
  <h2>Resultado principal</h2><div class="metrics"><div class="metric primary"><span class="metric-label">Cumplimiento BPM</span><strong>${number(data.calculation.bpmPercentage)} %</strong></div><div class="metric"><span class="metric-label">Riesgo del producto</span><strong>${number(data.calculation.productRiskScore)} · ${productRisk[Number(data.calculation.productRiskScore)]||'—'}</strong></div><div class="metric"><span class="metric-label">Riesgo total</span><strong>${number(data.calculation.totalRiskScore)}</strong></div><div class="metric"><span class="metric-label">Frecuencia</span><strong>${escapeHtml(frequency[data.calculation.frequency]||data.calculation.frequency)}</strong></div></div>
  <div class="progress" aria-label="Cumplimiento BPM"><span></span></div><p class="small">Riesgo del establecimiento: <strong>${number(data.calculation.establishmentRiskScore)}</strong>. La frecuencia se determina con las reglas vigentes usadas en esta inspección.</p>
  <h2>Resumen ejecutivo</h2>${narrative(data.narrative.executiveSummary,`Inspección BPM con ${number(data.calculation.bpmPercentage)} % de cumplimiento y frecuencia ${frequency[data.calculation.frequency]||data.calculation.frequency}. Revise los hallazgos y las evidencias antes de decidir acciones.`)}
  <h2>Hallazgos relevantes</h2><p>${findings.length} criterios requieren atención: ${nonconformities.length} incumplidos y ${findings.length-nonconformities.length} parcialmente cumplidos.</p>${findings.length?`<table><thead><tr><th style="width:17%">Criterio</th><th style="width:20%">Resultado</th><th>Hallazgo u observación</th></tr></thead><tbody>${findings.map(x=>row([x.code||'—',response[x.value]||x.value,x.observations||x.title||'Sin observación registrada'])).join('')}</tbody></table>`:'<p class="empty">No se registraron criterios incumplidos ni parcialmente cumplidos.</p>'}${narrative(data.narrative.additionalFindings,'No se agregaron hallazgos adicionales.')}
  <h2>No conformidades</h2>${nonconformities.length?`<table><thead><tr><th style="width:17%">Criterio</th><th>Descripción</th></tr></thead><tbody>${nonconformities.map(x=>row([x.code||'—',x.observations||x.title||'Incumplimiento registrado'])).join('')}</tbody></table>`:'<p class="empty">No se registraron criterios incumplidos.</p>'}
  <h2>Recomendaciones</h2>${narrative(data.narrative.recommendations,'No se registraron recomendaciones específicas para esta inspección.')}
  <h2>Resultados BPM</h2>${data.bpm.length?`<table><thead><tr><th style="width:70%">Criterio</th><th style="width:30%">Resultado</th></tr></thead><tbody>${data.bpm.map(x=>row([`${x.code||'—'} · ${x.title||'Criterio'}`,response[x.value]||x.value])).join('')}</tbody></table>`:'<p class="empty">No hay respuestas BPM registradas.</p>'}
  <h2>Factores de riesgo</h2>${data.factors.length?`<table><thead><tr><th style="width:31%">Factor</th><th style="width:35%">Selección</th><th style="width:12%">Peso</th><th style="width:10%">Puntaje</th><th style="width:12%">Aporte</th></tr></thead><tbody>${data.factors.map(x=>row([x.name,x.selectedLabel||'—',`${number(Number(x.weight)*100)} %`,number(x.score),number(x.contribution)])).join('')}</tbody></table>`:'<p class="empty">No hay factores de riesgo registrados.</p>'}
  <h2>Anexos y evidencias</h2>${data.evidence.length?`<table><thead><tr><th>Archivo</th><th>Criterio</th><th>Tipo</th><th>Estado</th></tr></thead><tbody>${data.evidence.map(x=>row([x.fileName||x.id,x.criterionCode||'General',x.mimeType,x.status==='VALID'?'Validada':x.status==='REJECTED'?'Rechazada':'Registrada'])).join('')}</tbody></table><p class="small">Los originales se conservan en el expediente privado de la inspección. Los documentos y vídeos se consultan desde ese expediente.</p>${data.evidence.filter(x=>x.imageDataUrl).map(x=>`<figure class="photo"><img src="${escapeHtml(x.imageDataUrl)}" alt="Evidencia ${escapeHtml(x.fileName)}"><figcaption>${escapeHtml(x.fileName)} · Criterio ${escapeHtml(x.criterionCode||'General')}</figcaption></figure>`).join('')}`:'<p class="empty">No hay evidencias vinculadas.</p>'}
  <h2>Historial de revisión</h2>${data.history.length?`<table><thead><tr><th>Acción</th><th>Fecha</th></tr></thead><tbody>${data.history.map(x=>row([event[x.eventType]||x.eventType,date(x.occurredAt)])).join('')}</tbody></table>`:'<p class="empty">Sin eventos de revisión.</p>'}
  ${draft?'<p class="small">Este borrador no constituye un informe oficial. Revise su contenido antes de oficializarlo.</p>':`<h2>Espacios para firma</h2><div class="signature-area"><div class="signature"><div class="signature-line">Firma del evaluador<br><strong>${escapeHtml(data.inspection.evaluator)}</strong></div></div><div class="signature"><div class="signature-line">Firma de quien aprueba<br><strong>${escapeHtml(data.inspection.approver)}</strong></div></div></div><p class="small">Espacios reservados para firma electrónica. Este PDF no contiene una firma digital aplicada.</p>`}
  <footer class="footer">SIRA Tech · Verificación ${escapeHtml(data.verificationId)} · Generado ${date(data.generatedAt)} · Caso ${escapeHtml(data.case.id)} · Inspección ${escapeHtml(data.inspection.id)}</footer>
  </body></html>`;
}
export const buildOfficialReportHtml=(data:ReportData)=>buildReportHtml(data,'OFFICIAL');
export const buildDraftReportHtml=(data:ReportData)=>buildReportHtml(data,'DRAFT');
export { escapeHtml };
