import { createHash, randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { env } from '../../config/env.js';
import { writeDomainAudit } from '../../core/audit/domain-audit.service.js';
import type { RoleCode } from '../../core/auth/roles.js';
import { createShortLivedDownloadUrl, readPrivateObject, removePrivateObject, uploadPrivateObject } from '../../core/storage/storage.service.js';
import { createUploadPath } from '../../core/storage/storage-path.js';
import { query, withTransaction } from '../../db/client.js';
import { buildOfficialReportHtml, type ReportData } from './report-template.js';
import { renderPdf } from './report-renderer.js';

export type Actor={userId:string;role:RoleCode;authTime:number};
export type ReviewErrorCode='FORBIDDEN'|'NOT_FOUND'|'CONFLICT'|'STALE_VERSION'|'VALIDATION_ERROR'|'REAUTHENTICATION_REQUIRED'|'PAYLOAD_TOO_LARGE';
export class ReviewError extends Error{constructor(public code:ReviewErrorCode,public details?:unknown){super(code)}}
const globalRoles=new Set<RoleCode>(['ADMIN','UNIVERSAL','COORDINATOR']);
const operationalRoles=new Set<RoleCode>(['UNIVERSAL','COORDINATOR']);
const internalRoles=new Set<RoleCode>([...globalRoles,'EVALUATOR']);
const audit=(client:PoolClient|undefined,action:string,actor:Actor,correlationId:string,entityType:string,entityId:string,metadata:Record<string,string|number|boolean|null>)=>writeDomainAudit({action,actorUserId:actor.userId,correlationId,entityType,entityId,metadata,client});
const exceptional=(actor:Actor)=>actor.role==='ADMIN'||actor.role==='UNIVERSAL';
const runQuery=<T extends import('pg').QueryResultRow=any>(client:PoolClient|undefined,sql:string,values:unknown[]=[])=>client?client.query<T>(sql,values):query<T>(sql,values);
function readRole(actor:Actor){if(!internalRoles.has(actor.role))throw new ReviewError('FORBIDDEN')}
function globalRole(actor:Actor){if(!operationalRoles.has(actor.role))throw new ReviewError('FORBIDDEN')}
function requireRecentExceptional(actor:Actor){globalRole(actor);if(exceptional(actor)&&Math.floor(Date.now()/1000)-actor.authTime>env.JWT_REAUTH_MAX_AGE_MINUTES*60)throw new ReviewError('REAUTHENTICATION_REQUIRED')}
async function inspectionAccess(id:string,actor:Actor,client?:PoolClient,lock=false){readRole(actor);const result=await runQuery(client,`SELECT i.id,i.case_id AS "caseId",i.evaluator_user_id AS "evaluatorUserId",i.status::text,i.version,i.content_revision AS "contentRevision" FROM inspections i WHERE i.id=$1${lock?' FOR UPDATE':''}`,[id]);const row=result.rows[0];if(!row)throw new ReviewError('NOT_FOUND');if(actor.role==='EVALUATOR'&&row.evaluatorUserId!==actor.userId)throw new ReviewError('FORBIDDEN');return row}
const reviewProjection=`r.id,r.inspection_id AS "inspectionId",r.cycle_number AS "cycleNumber",r.status::text,r.reviewer_user_id AS "reviewerUserId",r.initial_calculation_id AS "initialCalculationId",r.current_calculation_id AS "currentCalculationId",r.return_count AS "returnCount",r.return_reason AS "returnReason",r.resubmitted_at AS "resubmittedAt",r.approved_at AS "approvedAt",r.approved_by_user_id AS "approvedByUserId",r.version,r.created_at AS "createdAt",r.updated_at AS "updatedAt"`;
const reportProjection=`id,inspection_id AS "inspectionId",review_cycle_id AS "reviewId",calculation_id AS "calculationId",status::text,file_name AS "fileName",mime_type AS "mimeType",size_bytes::int AS "sizeBytes",verification_id AS "verificationId",generated_by_user_id AS "generatedByUserId",generated_at AS "generatedAt",official_at AS "officialAt",official_by_user_id AS "officialByUserId",version,generated_at AS "createdAt",updated_at AS "updatedAt"`;
async function review(id:string,reviewId:string,actor:Actor,client?:PoolClient,lock=false){await inspectionAccess(id,actor,client,lock);const result=await runQuery(client,`SELECT ${reviewProjection} FROM inspection_review_cycles r WHERE r.inspection_id=$1 AND r.id=$2${lock?' FOR UPDATE':''}`,[id,reviewId]);if(!result.rows[0])throw new ReviewError('NOT_FOUND');return result.rows[0]}
async function fullReview(id:string,reviewId:string,actor:Actor){const row=await review(id,reviewId,actor);const [items,events]=await Promise.all([query<any>(`SELECT x.id,x.bpm_item_id AS "bpmItemId",x.return_number AS "returnNumber",x.status::text,x.response_version_at_return AS "responseVersionAtReturn",x.corrected_response_version AS "correctedResponseVersion",x.corrected_at AS "correctedAt" FROM inspection_review_correction_items x WHERE x.review_cycle_id=$1 ORDER BY x.return_number,x.id`,[reviewId]),query<any>(`SELECT id,event_type AS "eventType",actor_user_id AS "actorUserId",calculation_id AS "calculationId",occurred_at AS "occurredAt" FROM inspection_review_events WHERE review_cycle_id=$1 ORDER BY occurred_at,id`,[reviewId])]);return{...row,correctionItems:items.rows,events:events.rows}}

export async function openReview(id:string,actor:Actor,correlationId:string){globalRole(actor);return withTransaction(async client=>{await inspectionAccess(id,actor,client,true);const result=await client.query<{id:string}>('SELECT open_inspection_review($1,$2) id',[id,actor.userId]);const reviewId=result.rows[0].id;const row=(await client.query<any>(`SELECT ${reviewProjection} FROM inspection_review_cycles r WHERE r.id=$1`,[reviewId])).rows[0];await audit(client,'REVIEW_OPENED',actor,correlationId,'INSPECTION_REVIEW',reviewId,{inspectionId:id,reviewId,cycleNumber:row.cycleNumber,exceptionalIntervention:exceptional(actor)});return row})}
export async function reviews(id:string,actor:Actor){await inspectionAccess(id,actor);return(await query<any>(`SELECT ${reviewProjection} FROM inspection_review_cycles r WHERE r.inspection_id=$1 ORDER BY r.cycle_number DESC`,[id])).rows}
export async function currentReview(id:string,actor:Actor){await inspectionAccess(id,actor);const row=(await query<any>(`SELECT ${reviewProjection} FROM inspection_review_cycles r WHERE r.inspection_id=$1 ORDER BY (r.status<>'APPROVED') DESC,r.cycle_number DESC LIMIT 1`,[id])).rows[0];if(!row)throw new ReviewError('NOT_FOUND');return fullReview(id,row.id,actor)}
export const reviewDetail=fullReview;
export async function returnReview(id:string,reviewId:string,input:{reason:string;bpmItemIds:string[]},actor:Actor,correlationId:string){requireRecentExceptional(actor);return withTransaction(async client=>{await review(id,reviewId,actor,client,true);await client.query('SELECT return_inspection_review($1,$2,$3,$4,$5::uuid[])',[id,reviewId,actor.userId,input.reason,input.bpmItemIds]);const row=(await client.query<any>(`SELECT ${reviewProjection} FROM inspection_review_cycles r WHERE r.id=$1`,[reviewId])).rows[0];await audit(client,'REVIEW_RETURNED',actor,correlationId,'INSPECTION_REVIEW',reviewId,{inspectionId:id,reviewId,cycleNumber:row.cycleNumber,returnNumber:row.returnCount,criteriaCount:input.bpmItemIds.length,exceptionalIntervention:exceptional(actor)});return row})}
async function correctionContext(client:PoolClient,id:string,reviewId:string,itemId:string,actor:Actor,baseVersion:number){if(actor.role!=='EVALUATOR')throw new ReviewError('FORBIDDEN');const ins=await inspectionAccess(id,actor,client,true);if(ins.version!==baseVersion)throw new ReviewError('STALE_VERSION');const row=(await client.query<any>(`SELECT r.id FROM inspection_review_cycles r JOIN inspection_review_correction_items x ON x.review_cycle_id=r.id WHERE r.id=$2 AND r.inspection_id=$1 AND r.status='RETURNED_FOR_CORRECTION' AND x.return_number=r.return_count AND x.bpm_item_id=$3 AND x.status='OPEN' FOR UPDATE OF r,x`,[id,reviewId,itemId])).rows[0];if(!row)throw new ReviewError('NOT_FOUND');await client.query("SELECT set_config('app.actor_user_id',$1,true),set_config('app.review_correction_write',$2,true)",[actor.userId,reviewId]);return ins}
export async function updateCorrection(id:string,reviewId:string,itemId:string,input:{baseVersion:number;responseValue:string;observations?:string|null},actor:Actor,correlationId:string){return withTransaction(async client=>{await correctionContext(client,id,reviewId,itemId,actor,input.baseVersion);const changed=await client.query<any>(`INSERT INTO inspection_bpm_responses(inspection_id,bpm_item_id,response_value,observations) VALUES($1,$2,$3,$4) ON CONFLICT(inspection_id,bpm_item_id) DO UPDATE SET response_value=EXCLUDED.response_value,observations=EXCLUDED.observations RETURNING version`,[id,itemId,input.responseValue,input.observations??null]);const ins=(await client.query<any>('SELECT version,content_revision AS "contentRevision" FROM inspections WHERE id=$1',[id])).rows[0];await audit(client,'REVIEW_CORRECTION_UPDATED',actor,correlationId,'INSPECTION_REVIEW',reviewId,{inspectionId:id,reviewId,bpmItemId:itemId,responseVersion:changed.rows[0].version,inspectionVersion:ins.version,contentRevision:ins.contentRevision});return{bpmItemId:itemId,responseVersion:changed.rows[0].version,version:ins.version,contentRevision:ins.contentRevision}})}
export async function removeCorrection(id:string,reviewId:string,itemId:string,baseVersion:number,actor:Actor,correlationId:string){return withTransaction(async client=>{await correctionContext(client,id,reviewId,itemId,actor,baseVersion);const removed=await client.query('DELETE FROM inspection_bpm_responses WHERE inspection_id=$1 AND bpm_item_id=$2',[id,itemId]);if(!removed.rowCount)throw new ReviewError('NOT_FOUND');const ins=(await client.query<any>('SELECT version,content_revision AS "contentRevision" FROM inspections WHERE id=$1',[id])).rows[0];await audit(client,'REVIEW_CORRECTION_REMOVED',actor,correlationId,'INSPECTION_REVIEW',reviewId,{inspectionId:id,reviewId,bpmItemId:itemId,inspectionVersion:ins.version,contentRevision:ins.contentRevision});return{removed:true,version:ins.version,contentRevision:ins.contentRevision}})}
export async function resubmit(id:string,reviewId:string,actor:Actor,correlationId:string){if(actor.role!=='EVALUATOR')throw new ReviewError('FORBIDDEN');return withTransaction(async client=>{await review(id,reviewId,actor,client,true);const calculationId=(await client.query<{id:string}>('SELECT resubmit_inspection_review($1,$2,$3) id',[id,reviewId,actor.userId])).rows[0].id;await audit(client,'REVIEW_RESUBMITTED',actor,correlationId,'INSPECTION_REVIEW',reviewId,{inspectionId:id,reviewId,calculationId});return{reviewId,calculationId,status:'RESUBMITTED'}})}
export async function approveReview(id:string,reviewId:string,note:string|undefined,actor:Actor,correlationId:string){requireRecentExceptional(actor);return withTransaction(async client=>{await review(id,reviewId,actor,client,true);await client.query('SELECT approve_inspection_review($1,$2,$3,$4)',[id,reviewId,actor.userId,note??null]);const row=(await client.query<any>(`SELECT ${reviewProjection} FROM inspection_review_cycles r WHERE r.id=$1`,[reviewId])).rows[0];await audit(client,'REVIEW_APPROVED',actor,correlationId,'INSPECTION_REVIEW',reviewId,{inspectionId:id,reviewId,cycleNumber:row.cycleNumber,calculationId:row.currentCalculationId,exceptionalIntervention:exceptional(actor)});return row})}

async function reportRow(id:string,reportId:string,actor:Actor,includePath=false,client?:PoolClient,lock=false){await inspectionAccess(id,actor,client,lock);const result=await runQuery(client,`SELECT ${reportProjection}${includePath?',storage_path AS "storagePath",content_sha256 AS "contentSha256"':''} FROM inspection_reports WHERE inspection_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[id,reportId]);if(!result.rows[0])throw new ReviewError('NOT_FOUND');return result.rows[0]}
export async function reports(id:string,actor:Actor){await inspectionAccess(id,actor);return(await query<any>(`SELECT ${reportProjection} FROM inspection_reports WHERE inspection_id=$1 AND archived_at IS NULL ORDER BY generated_at DESC`,[id])).rows}
export const reportDetail=(id:string,reportId:string,actor:Actor)=>reportRow(id,reportId,actor);
async function reportData(id:string,verificationId:string,generatedAt:string):Promise<ReportData>{
  const head=(await query<any>(`SELECT i.id,i.started_at,c.id AS case_id,c.origin::text,co.legal_name AS company,e.name AS establishment,u.full_name AS evaluator,r.approved_by_name_snapshot AS approver,bt.name||' v'||bv.version_number AS bpm,rs.name||' v'||rv.version_number AS risk,ic.id AS calculation_id,ic.bpm_percentage,ic.product_risk_score,ic.establishment_risk_score,ic.total_risk_score,ic.frequency::text FROM inspections i JOIN cases c ON c.id=i.case_id LEFT JOIN companies co ON co.id=c.company_id LEFT JOIN establishments e ON e.id=c.establishment_id JOIN users u ON u.id=i.evaluator_user_id JOIN inspection_review_cycles r ON r.inspection_id=i.id AND r.status='APPROVED' JOIN inspection_calculations ic ON ic.id=r.current_calculation_id JOIN bpm_template_versions bv ON bv.id=i.bpm_template_version_id JOIN bpm_templates bt ON bt.id=bv.template_id JOIN risk_rule_versions rv ON rv.id=i.risk_rule_version_id JOIN risk_rule_sets rs ON rs.id=rv.risk_rule_set_id WHERE i.id=$1 ORDER BY r.cycle_number DESC LIMIT 1`,[id])).rows[0];if(!head)throw new ReviewError('CONFLICT');
  const [bpm,factors,evidence,history]=await Promise.all([query<any>('SELECT display_code_snapshot AS code,response_value::text AS value,is_applicable AS applicable FROM inspection_calculation_bpm_snapshots WHERE calculation_id=$1 ORDER BY id',[head.calculation_id]),query<any>('SELECT factor_code_snapshot AS code,factor_name_snapshot AS name,weight_snapshot AS weight,selected_score_snapshot AS score,weighted_contribution AS contribution FROM inspection_calculation_factor_snapshots WHERE calculation_id=$1 ORDER BY sort_order_snapshot',[head.calculation_id]),query<any>("SELECT id,mime_type AS \"mimeType\",size_bytes::int AS \"sizeBytes\",status::text FROM inspection_evidence WHERE inspection_id=$1 AND status<>'ARCHIVED' ORDER BY created_at",[id]),query<any>('SELECT event_type AS "eventType",occurred_at AS "occurredAt" FROM inspection_review_events WHERE inspection_id=$1 ORDER BY occurred_at',[id])]);
  return{verificationId,generatedAt,case:{id:head.case_id,origin:head.origin,company:head.company,establishment:head.establishment},inspection:{id,date:head.started_at,evaluator:head.evaluator,approver:head.approver,bpmTemplate:head.bpm,riskRule:head.risk},calculation:{bpmPercentage:head.bpm_percentage,productRiskScore:head.product_risk_score,establishmentRiskScore:head.establishment_risk_score,totalRiskScore:head.total_risk_score,frequency:head.frequency},bpm:bpm.rows,factors:factors.rows,evidence:evidence.rows,history:history.rows};
}
export async function generateReport(id:string,operationId:string,actor:Actor,correlationId:string){
  globalRole(actor);
  await inspectionAccess(id,actor);
  const existing=(await query<any>(`SELECT ${reportProjection} FROM inspection_reports WHERE generation_key=$1`,[operationId])).rows[0];
  if(existing){if(existing.inspectionId!==id)throw new ReviewError('CONFLICT');return existing}

  const verificationId=randomUUID(),generatedAt=new Date().toISOString(),data=await reportData(id,verificationId,generatedAt),pdf=await renderPdf(buildOfficialReportHtml(data));
  if(pdf.length>5*1024*1024)throw new ReviewError('PAYLOAD_TOO_LARGE');
  if(pdf.subarray(0,5).toString()!=='%PDF-')throw new ReviewError('CONFLICT');
  const storagePath=createUploadPath('official-report',id,'application/pdf'),sha=createHash('sha256').update(pdf).digest('hex');
  await uploadPrivateObject({storagePath,mimeType:'application/pdf',content:pdf});

  let result:{report:any;reused:boolean;oldPath?:string};
  try{
    result=await withTransaction(async client=>{
      await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`inspection-report-operation:${operationId}`]);
      await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`inspection-report-inspection:${id}`]);
      const lockedExisting=(await client.query<any>(`SELECT ${reportProjection} FROM inspection_reports WHERE generation_key=$1 FOR UPDATE`,[operationId])).rows[0];
      if(lockedExisting){
        if(lockedExisting.inspectionId!==id)throw new ReviewError('CONFLICT');
        return{report:lockedExisting,reused:true};
      }

      await inspectionAccess(id,actor,client,true);
      const approved=(await client.query<any>("SELECT id,current_calculation_id AS \"calculationId\",approved_by_user_id AS \"approverId\",approved_by_name_snapshot AS \"approverName\",approved_by_role_snapshot AS \"approverRole\" FROM inspection_review_cycles WHERE inspection_id=$1 AND status='APPROVED' ORDER BY cycle_number DESC LIMIT 1 FOR UPDATE",[id])).rows[0];
      if(!approved)throw new ReviewError('CONFLICT');
      const prior=(await client.query<any>("SELECT id,storage_path AS \"storagePath\",calculation_id AS \"calculationId\" FROM inspection_reports WHERE inspection_id=$1 AND status='DRAFT' AND archived_at IS NULL FOR UPDATE",[id])).rows[0];
      if(prior){
        await client.query("SELECT set_config('app.report_archive_calculation_id',$1,true)",[prior.calculationId]);
        await client.query('UPDATE inspection_reports SET archived_at=clock_timestamp(),archived_by_user_id=$1 WHERE id=$2',[actor.userId,prior.id]);
      }
      await client.query("SELECT set_config('app.report_generation_review_id',$1,true)",[approved.id]);
      const inserted=(await client.query<any>(`INSERT INTO inspection_reports(inspection_id,review_cycle_id,calculation_id,generation_key,verification_id,storage_path,file_name,mime_type,size_bytes,content_sha256,generated_by_user_id,generated_at) VALUES($1,$2,$3,$4,$5,$6,$7,'application/pdf',$8,$9,$10,$11) RETURNING ${reportProjection}`,[id,approved.id,approved.calculationId,operationId,verificationId,storagePath,`inspection-${id}.pdf`,pdf.length,sha,actor.userId,generatedAt])).rows[0];
      const participants=await client.query<any>('SELECT i.evaluator_user_id AS evaluator_id,u.full_name evaluator_name,rr.name evaluator_role FROM inspections i JOIN users u ON u.id=i.evaluator_user_id JOIN roles rr ON rr.id=u.role_id WHERE i.id=$1',[id]);
      const p=participants.rows[0];
      await client.query(`INSERT INTO inspection_report_participants(report_id,participant_role,user_id,display_name_snapshot,role_name_snapshot,participation_snapshot) VALUES($1,'EVALUATOR',$2,$3,$4,'Evaluador responsable'),($1,'COORDINATOR_APPROVER',$5,$6,$7,'Aprobación de revisión')`,[inserted.id,p.evaluator_id,p.evaluator_name,p.evaluator_role,approved.approverId,approved.approverName,approved.approverRole]);
      await audit(client,prior?'REPORT_DRAFT_REGENERATED':'REPORT_DRAFT_GENERATED',actor,correlationId,'INSPECTION_REPORT',inserted.id,{inspectionId:id,reviewId:approved.id,reportId:inserted.id,calculationId:approved.calculationId,sizeBytes:pdf.length,exceptionalIntervention:exceptional(actor)});
      return{report:inserted,reused:false,oldPath:prior?.storagePath};
    });
  }catch(error){
    try{await removePrivateObject(storagePath)}catch{}
    throw error;
  }

  if(result.reused){
    try{await removePrivateObject(storagePath)}catch{}
    return result.report;
  }
  if(result.oldPath)try{await removePrivateObject(result.oldPath)}catch{}
  return result.report;
}
export async function officialize(id:string,reportId:string,actor:Actor,correlationId:string){requireRecentExceptional(actor);const stored=await reportRow(id,reportId,actor,true);const bytes=await readPrivateObject(stored.storagePath);if(bytes.length!==Number(stored.sizeBytes)||createHash('sha256').update(bytes).digest('hex')!==stored.contentSha256)throw new ReviewError('CONFLICT');return withTransaction(async client=>{await reportRow(id,reportId,actor,true,client,true);await client.query('SELECT officialize_inspection_report($1,$2,$3)',[id,reportId,actor.userId]);const row=await reportRow(id,reportId,actor,false,client);await audit(client,'REPORT_OFFICIALIZED',actor,correlationId,'INSPECTION_REPORT',reportId,{inspectionId:id,reportId,reviewId:row.reviewId,calculationId:row.calculationId,exceptionalIntervention:exceptional(actor)});return row})}
export async function download(id:string,reportId:string,actor:Actor,correlationId:string){const row=await reportRow(id,reportId,actor,true);if(row.status!=='OFFICIAL'&&actor.role==='EVALUATOR')throw new ReviewError('FORBIDDEN');const signed=await createShortLivedDownloadUrl(row.storagePath,60);await audit(undefined,'REPORT_DOWNLOAD_ISSUED',actor,correlationId,'INSPECTION_REPORT',reportId,{inspectionId:id,reportId,status:row.status,expiresInSeconds:60});return signed}
export async function closeInspection(id:string,reportId:string,reason:string|undefined,actor:Actor,correlationId:string){requireRecentExceptional(actor);return withTransaction(async client=>{await reportRow(id,reportId,actor,false,client,true);const closureId=(await client.query<{id:string}>('SELECT close_inspection($1,$2,$3,$4) id',[id,reportId,actor.userId,reason??null])).rows[0].id;const row=(await client.query<any>('SELECT id,inspection_id AS "inspectionId",case_id AS "caseId",official_report_id AS "reportId",closed_by_user_id AS "closedByUserId",closed_at AS "closedAt",closure_reason AS reason FROM inspection_closures WHERE id=$1',[closureId])).rows[0];await audit(client,'INSPECTION_CLOSED',actor,correlationId,'INSPECTION_CLOSURE',closureId,{inspectionId:id,closureId,caseId:row.caseId,reportId,exceptionalIntervention:exceptional(actor)});return row})}
export async function closure(id:string,actor:Actor){await inspectionAccess(id,actor);const row=(await query<any>('SELECT id,inspection_id AS "inspectionId",case_id AS "caseId",official_report_id AS "reportId",closed_by_user_id AS "closedByUserId",closed_at AS "closedAt",closure_reason AS reason FROM inspection_closures WHERE inspection_id=$1',[id])).rows[0];if(!row)throw new ReviewError('NOT_FOUND');return row}
