import { randomUUID } from 'node:crypto';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import ExcelJS from 'exceljs';
import { describe, expect, it } from 'vitest';
import { query } from '../../db/client.js';
import { importBpm } from '../../modules/official-imports/service.js';
import { canonicalJson, sha256 } from '../../modules/official-imports/model.js';
import type { BpmManifest } from '../../modules/official-imports/manifests.js';

async function fixture(withGuidance=true){const directory=await mkdtemp(path.join(tmpdir(),'ebr-import-idempotency-')),allItems=path.join(directory,'all-items.sql'),guide=path.join(directory,'guide.xlsx'),suffix=randomUUID().replaceAll('-','').slice(0,10).toUpperCase();await writeFile(allItems,`INSERT [dbo].[AllItems] ([Items], [ItemsId], [Decription], [SectionType], [Parents]) VALUES (1, N'1', N'1. SECTION', N'C', NULL)\nINSERT [dbo].[AllItems] ([Items], [ItemsId], [Decription], [SectionType], [Parents]) VALUES (2, N'1.1', N'1.1 Subsection', N'S', N'1')\nINSERT [dbo].[AllItems] ([Items], [ItemsId], [Decription], [SectionType], [Parents]) VALUES (3, N'1.1.1', N'Inspection criterion', N'I', N'1.1')`,'utf8');const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Guide');sheet.getCell('A1').value='Inspection criterion';sheet.getCell('P1').value='Observaciones';sheet.getCell('X1').value='Puntos';if(withGuidance){sheet.getCell('A2').value='C';sheet.getCell('B2').value='i. Atomic guidance'}await workbook.xlsx.writeFile(guide);const manifest:BpmManifest={schemaVersion:1,importType:'BPM',template:{code:`BPM_IDEMP_${suffix}`,name:'Idempotency fixture'},allItems:{logicalName:'allItems',path:allItems},workbooks:[{logicalName:'guide',path:guide,sheet:'Guide'}],guide:{logicalName:'guide',sheet:'Guide'},allItemsOverrides:[]};return{manifest,hash:sha256(canonicalJson({suffix,withGuidance}))}}

describe('official import idempotency and atomic rejection',()=>{it('produces one concurrent effect and no functional writes for a rejected package',async()=>{const valid=await fixture(),actor={label:'integration-import-test'};expect((await importBpm(valid.manifest,valid.hash,'DRY_RUN',actor)).status).toBe('SUCCEEDED');const concurrent=await Promise.all([importBpm(valid.manifest,valid.hash,'APPLY',actor),importBpm(valid.manifest,valid.hash,'APPLY',actor)]);expect(concurrent.map(report=>report.status).sort()).toEqual(['SKIPPED','SUCCEEDED']);const successful=concurrent.find(report=>report.status==='SUCCEEDED')!;expect((await query<any>('SELECT status::text FROM bpm_template_versions WHERE id=$1',[successful.createdVersions.bpmTemplateVersionId])).rows[0].status).toBe('DRAFT');const invalid=await fixture(false),report=await importBpm(invalid.manifest,invalid.hash,'APPLY',actor);expect(report.status).toBe('REJECTED');expect(report.createdVersions).toEqual({});expect((await query('SELECT 1 FROM bpm_templates WHERE code=$1',[invalid.manifest.template.code])).rowCount).toBe(0)},30000)});
