import { Router, type Request, type Response } from 'express';
import { authenticate } from '../../core/auth/authenticate.js';
import { bad, ok } from '../cases/http.js';
import { DefinitionError } from '../versioned-definitions/common.js';
import * as z from './schemas.js';
import * as s from './service.js';

const router = Router();
router.use(authenticate);
const actor = (request: Request) => request.auth!;
const fail = (request: Request, response: Response, error: unknown) => {
  if (error instanceof DefinitionError) {
    const status = { FORBIDDEN: 403, NOT_FOUND: 404, CONFLICT: 409, STALE_VERSION: 409, VALIDATION_ERROR: 400, REAUTHENTICATION_REQUIRED: 401, PUBLICATION_INVALID: 422 }[error.code];
    return response.status(status).json({ error: { code: error.code, message: 'La operación no pudo completarse.', ...(error.details ? { details: error.details } : {}) }, meta: { correlationId: request.context.correlationId } });
  }
  if (['23505', '23514', '23P01', '55000'].includes((error as any)?.code)) return bad(request, response, 409, 'CONFLICT');
  throw error;
};
const wrap = (handler: (request: Request, response: Response) => Promise<unknown>) => async (request: Request, response: Response, next: any) => {
  try { await handler(request, response); } catch (error) { try { fail(request, response, error); } catch (nextError) { next(nextError); } }
};
const ids = (request: Request) => [z.uuid.safeParse(request.params.templateId), z.uuid.safeParse(request.params.versionId), z.uuid.safeParse(request.params.itemId)] as const;

router.get('/', wrap(async (request, response) => ok(request, response, await s.list(actor(request)))));
router.post('/', wrap(async (request, response) => { const parsed = z.createTemplateSchema.safeParse(request.body); if (!parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.create(parsed.data, actor(request), request.context.correlationId), 201); }));
router.post('/:templateId/set-default', wrap(async (request, response) => { const [templateId] = ids(request); const parsed = z.retireSchema.safeParse(request.body); if (!templateId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.setDefault(templateId.data, parsed.data.version, actor(request), request.context.correlationId)); }));
router.get('/:templateId', wrap(async (request, response) => { const [templateId] = ids(request); if (!templateId.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.detail(templateId.data, actor(request))); }));
router.get('/:templateId/versions', wrap(async (request, response) => { const [templateId] = ids(request); if (!templateId.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.versions(templateId.data, actor(request))); }));
router.post('/:templateId/versions', wrap(async (request, response) => { const [templateId] = ids(request); const parsed = z.createVersionSchema.safeParse(request.body); if (!templateId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.createVersion(templateId.data, parsed.data.cloneFromVersionId, actor(request), request.context.correlationId), 201); }));
router.get('/:templateId/versions/:versionId', wrap(async (request, response) => { const [templateId, versionId] = ids(request); if (!templateId.success || !versionId.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.versionDetail(templateId.data, versionId.data, actor(request))); }));
router.get('/:templateId/versions/:versionId/preview', wrap(async (request, response) => { const [templateId, versionId] = ids(request); if (!templateId.success || !versionId.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.preview(templateId.data, versionId.data, actor(request))); }));
router.get('/:templateId/versions/:versionId/validate', wrap(async (request, response) => { const [templateId, versionId] = ids(request); if (!templateId.success || !versionId.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.validate(templateId.data, versionId.data, actor(request), request.context.correlationId)); }));
router.post('/:templateId/versions/:versionId/publish', wrap(async (request, response) => { const [templateId, versionId] = ids(request); const parsed = z.publishSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.publish(templateId.data, versionId.data, parsed.data, actor(request), request.context.correlationId)); }));
router.post('/:templateId/versions/:versionId/retire', wrap(async (request, response) => { const [templateId, versionId] = ids(request); const parsed = z.retireSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.retire(templateId.data, versionId.data, parsed.data.version, actor(request), request.context.correlationId)); }));
router.post('/:templateId/versions/:versionId/items', wrap(async (request, response) => { const [templateId, versionId] = ids(request); const parsed = z.createItemSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.createItem(templateId.data, versionId.data, parsed.data, actor(request), request.context.correlationId), 201); }));
router.patch('/:templateId/versions/:versionId/items/:itemId', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); const parsed = z.patchItemSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !itemId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.patchItem(templateId.data, versionId.data, itemId.data, parsed.data, actor(request), request.context.correlationId)); }));
router.post('/:templateId/versions/:versionId/items/:itemId/move', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); const parsed = z.moveItemSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !itemId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.moveItem(templateId.data, versionId.data, itemId.data, parsed.data, actor(request), request.context.correlationId)); }));
router.delete('/:templateId/versions/:versionId/items/:itemId', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); const parsed = z.deleteItemSchema.safeParse({ ...request.query, ...request.body }); if (!templateId.success || !versionId.success || !itemId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.deleteItem(templateId.data, versionId.data, itemId.data, parsed.data.version, actor(request), request.context.correlationId)); }));

router.get('/:templateId/versions/:versionId/items/:itemId/guidance', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); if (!templateId.success || !versionId.success || !itemId.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.listGuidance(templateId.data, versionId.data, itemId.data, actor(request))); }));
router.post('/:templateId/versions/:versionId/items/:itemId/guidance', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); const parsed = z.createGuidanceSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !itemId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.createGuidance(templateId.data, versionId.data, itemId.data, parsed.data, actor(request), request.context.correlationId), 201); }));
router.patch('/:templateId/versions/:versionId/items/:itemId/guidance/:guidanceId', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); const guidanceId = z.uuid.safeParse(request.params.guidanceId); const parsed = z.patchGuidanceSchema.safeParse(request.body); if (!templateId.success || !versionId.success || !itemId.success || !guidanceId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.patchGuidance(templateId.data, versionId.data, itemId.data, guidanceId.data, parsed.data, actor(request), request.context.correlationId)); }));
router.delete('/:templateId/versions/:versionId/items/:itemId/guidance/:guidanceId', wrap(async (request, response) => { const [templateId, versionId, itemId] = ids(request); const guidanceId = z.uuid.safeParse(request.params.guidanceId); const parsed = z.deleteGuidanceSchema.safeParse({ ...request.query, ...request.body }); if (!templateId.success || !versionId.success || !itemId.success || !guidanceId.success || !parsed.success) return bad(request, response, 400, 'VALIDATION_ERROR'); ok(request, response, await s.deleteGuidance(templateId.data, versionId.data, itemId.data, guidanceId.data, parsed.data.version, actor(request), request.context.correlationId)); }));

export default router;
