import type{QueryResult,QueryResultRow}from'pg';import type{ListInput}from'./schemas.js';
export type Runner={query:<T extends QueryResultRow>(sql:string,values?:unknown[])=>Promise<QueryResult<T>>};
const sourceJoins=' FROM cases c LEFT JOIN company_requests cr ON cr.id=c.request_id LEFT JOIN establishments ce ON ce.id=cr.establishment_id LEFT JOIN institutional_program_cases ip ON ip.case_id=c.id LEFT JOIN health_alerts ha ON ha.case_id=c.id LEFT JOIN complaints co ON co.case_id=c.id';
const projection=`SELECT c.id,c.origin::text,c.status::text,c.priority::text,c.company_id AS "companyId",c.establishment_id AS "establishmentId",c.version,c.created_at AS "createdAt",c.updated_at AS "updatedAt",cr.id AS "requestId",cr.request_type AS "requestType",cr.reason AS "requestReason",ce.name AS "requestEstablishmentName",ip.program_reference AS "programReference",ip.planned_date AS "plannedDate",ip.reason AS "programReason",ip.observations AS "programObservations",ha.alert_number AS "alertNumber",ha.alert_date AS "alertDate",ha.product_description AS "productDescription",ha.description AS "alertDescription",ha.decision::text AS "alertDecision",ha.decision_reason AS "alertDecisionReason",ha.decided_at AS "alertDecidedAt",ha.decided_by_user_id AS "alertDecidedByUserId",co.complaint_type AS "complaintType",co.received_at AS "receivedAt",co.description AS "complaintDescription",co.complainant_data AS "complainantData",co.decision::text AS "complaintDecision",co.decision_reason AS "complaintDecisionReason",co.referral_reason AS "referralReason",co.referral_destination AS "referralDestination",co.decided_at AS "complaintDecidedAt",co.decided_by_user_id AS "complaintDecidedByUserId",COALESCE(ip.version,ha.version,co.version,cr.version) AS "sourceVersion"${sourceJoins}`;
export async function company(r:Runner,id:string){const q=await r.query<{status:string}>('SELECT status::text status FROM companies WHERE id=$1',[id]);return q.rows[0]}
export async function establishment(r:Runner,id:string){const q=await r.query<{status:string;companyId:string}>('SELECT status::text status,company_id AS "companyId" FROM establishments WHERE id=$1',[id]);return q.rows[0]}
export async function insertCase(r:Runner,origin:string,status:string,priority:string,companyId?:string|null,establishmentId?:string|null){const q=await r.query<{id:string}>('INSERT INTO cases(origin,status,priority,company_id,establishment_id) VALUES($1,$2,$3,$4,$5) RETURNING id',[origin,status,priority,companyId??null,establishmentId??null]);return q.rows[0].id}
export async function find(r:Runner,id:string,lock=false){const q=await r.query(`${projection} WHERE c.id=$1 AND c.origin IN('COMPANY_REQUEST','INSTITUTIONAL_PROGRAM','HEALTH_ALERT','COMPLAINT')${lock?' FOR UPDATE OF c':''}`,[id]);return q.rows[0] as any}
export async function list(r:Runner,i:ListInput){const search=i.search?`%${i.search.toLowerCase()}%`:null,values=[i.origin??null,i.status??null,i.priority??null,i.companyId??null,i.establishmentId??null,i.dateFrom??null,i.dateTo??null,search],where=` WHERE c.origin IN('COMPANY_REQUEST','INSTITUTIONAL_PROGRAM','HEALTH_ALERT','COMPLAINT') AND ($1::case_origin IS NULL OR c.origin=$1) AND ($2::case_status IS NULL OR c.status=$2) AND ($3::priority_level IS NULL OR c.priority=$3) AND ($4::uuid IS NULL OR c.company_id=$4) AND ($5::uuid IS NULL OR c.establishment_id=$5) AND ($6::date IS NULL OR c.created_at::date>=$6) AND ($7::date IS NULL OR c.created_at::date<=$7) AND ($8::text IS NULL OR lower(COALESCE(cr.request_type,'')) LIKE $8 OR lower(COALESCE(ip.program_reference,'')) LIKE $8 OR lower(COALESCE(ha.alert_number,'')) LIKE $8 OR lower(COALESCE(co.complaint_type,'')) LIKE $8)`;const count=await r.query<{total:string}>(`SELECT count(*)::text total${sourceJoins}${where}`,values);const rows=await r.query(`${projection}${where} ORDER BY c.created_at DESC LIMIT $9 OFFSET $10`,[...values,i.limit,(i.page-1)*i.limit]);return{rows:rows.rows as any[],total:Number(count.rows[0]?.total??0)}}
export async function updateCaseOrganization(r:Runner,id:string,companyId:string|null,establishmentId:string|null){await r.query('UPDATE cases SET company_id=$1,establishment_id=$2 WHERE id=$3',[companyId,establishmentId,id])}
